'use client'
import { useCallback,useDeferredValue,useEffect,useMemo,useRef,useState } from 'react'
import { useRouter } from 'next/navigation'
import LayoutAdmin from '../../../components/LayoutAdmin'
import { supabase,type Empresa } from '../../../lib/supabase'
import { SALAO_ENABLED } from '../../../lib/salao/config'
import { consultarConferencia,desvincular,editarComissao,excluirComissao,setAnaliseManual,SITUACAO_LABEL,type LinhaConsulta } from '../../../lib/salao/conferencia'
import { formatarMoeda } from '../../../utils/calculoVT'

function mesAtual(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function mesesEntre(a:string,b:string){const out:string[]=[];let[y,m]=a.split('-').map(Number);const[fy,fm]=b.split('-').map(Number);while(y*12+m<=fy*12+fm&&out.length<24){out.push(`${y}-${String(m).padStart(2,'0')}`);m++;if(m>12){m=1;y++}}return out}
type Status='todos'|'com_nota'|'sem_nota'|'divergentes'|'analise'

export default function DadosImportadosPage(){
 const router=useRouter();const[inicio,setInicio]=useState(mesAtual());const[fim,setFim]=useState(mesAtual());const[empresaId,setEmpresaId]=useState('');const[status,setStatus]=useState<Status>('todos');const[busca,setBusca]=useState('');const buscaD=useDeferredValue(busca);const[empresas,setEmpresas]=useState<Empresa[]>([]);const[linhas,setLinhas]=useState<LinhaConsulta[]>([]);const[loading,setLoading]=useState(false);const[msg,setMsg]=useState('');const[pagina,setPagina]=useState(1);const[selecionada,setSelecionada]=useState<LinhaConsulta|null>(null);const[form,setForm]=useState<Record<string,string>>({});const[usuario,setUsuario]=useState<string|undefined>();const req=useRef(0);const[acao,setAcao]=useState('')
 useEffect(()=>{if(!SALAO_ENABLED){router.replace('/dashboard');return}supabase.from('empresas').select('*').order('razao_social').then(({data})=>setEmpresas(data||[]));supabase.auth.getUser().then(({data})=>setUsuario(data.user?.email))},[router])
 const carregar=useCallback(async()=>{const id=++req.current;if(!inicio||!fim||inicio>fim){setLinhas([]);setMsg('Informe um período válido.');return}setLoading(true);setMsg('');try{const buscarCompetencia=async(competencia:string)=>{const filtros={competencia,empresaId:empresaId||undefined};const primeira=await consultarConferencia(filtros,{campo:'nome',dir:'asc'},1,500);const paginas=Math.ceil(primeira.total/500);if(paginas<=1)return primeira.linhas;const restantes=await Promise.all(Array.from({length:paginas-1},(_,i)=>consultarConferencia(filtros,{campo:'nome',dir:'asc'},i+2,500)));return[...primeira.linhas,...restantes.flatMap(r=>r.linhas)]};const rs=await Promise.all(mesesEntre(inicio,fim).map(buscarCompetencia));if(id===req.current){const unicas=new Map<string,LinhaConsulta>();for(const l of rs.flat()){if(l.tipo==='comissao')unicas.set(l.id,l)}setLinhas([...unicas.values()])}}catch(e){if(id===req.current)setMsg(e instanceof Error?e.message:'Erro ao consultar dados importados.')}finally{if(id===req.current)setLoading(false)}},[inicio,fim,empresaId])
 useEffect(()=>{if(SALAO_ENABLED)carregar()},[carregar])
 const filtradas=useMemo(()=>{const q=buscaD.trim().toLowerCase();return linhas.filter(l=>(!q||`${l.nome} ${l.documento} ${l.empresaNome} ${l.nf_numero}`.toLowerCase().includes(q))&&(status==='todos'||status==='com_nota'&&!!l.nota_id||status==='sem_nota'&&!l.nota_id||status==='divergentes'&&(l.situacao==='conferido_com_divergencia'||l.situacao==='divergencia_valor')||status==='analise'&&!!l.analise_manual))},[linhas,buscaD,status])
 useEffect(()=>setPagina(1),[inicio,fim,empresaId,status,buscaD])
 const porPagina=50,totalPag=Math.max(1,Math.ceil(filtradas.length/porPagina)),visiveis=filtradas.slice((pagina-1)*porPagina,pagina*porPagina)
 const totais=useMemo(()=>({total:filtradas.length,comNota:filtradas.filter(l=>l.nota_id).length,semNota:filtradas.filter(l=>!l.nota_id).length,valor:filtradas.reduce((s,l)=>s+(l.valor_comissao||0),0)}),[filtradas])
 function editar(l:LinhaConsulta){setSelecionada(l);setForm({nome:l.nome||'',documento:l.documento||'',mes_ref:l.mes_ref,valor_comissao:String(l.valor_comissao||''),observacao:l.observacao||''})}
 async function salvar(){if(!selecionada||acao)return;setAcao('salvar');const r=await editarComissao(selecionada.id,form,usuario);setAcao('');if(!r.ok){setMsg(r.erro||'Erro ao salvar.');return}setMsg('Registro importado atualizado e reavaliado.');setSelecionada(null);carregar()}
 async function analisar(l:LinhaConsulta){if(acao)return;setAcao(l.id);const r=await setAnaliseManual('comissao',l.id,true,'Revisar dado importado',usuario);setAcao('');if(!r.ok){setMsg(r.erro||'Erro.');return}setMsg('Registro enviado para análise.');carregar()}
 async function excluir(l:LinhaConsulta){if(acao)return;setAcao(l.id);setLinhas(v=>v.filter(x=>x.id!==l.id));const r=await excluirComissao(l.id,usuario);setAcao('');if(!r.ok){setMsg(r.erro||'Erro ao excluir.');carregar();return}setMsg('Profissional excluído dos dados importados e registrado na auditoria.')}
 async function removerVinculo(l:LinhaConsulta){if(!l.nota_id||acao)return;setAcao(l.id);const r=await desvincular(l.id,l.nota_id);setAcao('');if(!r.ok){setMsg(r.erro||'Erro.');return}setMsg('Vínculo removido. O registro voltou para pendências.');carregar()}
 if(!SALAO_ENABLED)return null
 return <LayoutAdmin title="Salão — Dados importados"><div className="space-y-4">
  {msg&&<div className="rounded-lg border border-blue-200 bg-blue-50 p-3 text-sm text-blue-800">{msg}</div>}
  <section className="rounded-2xl bg-slate-900 p-4 text-white"><div className="flex flex-wrap items-end gap-3"><div className="mr-auto"><h1 className="text-lg font-semibold">Gestão dos dados importados</h1><p className="text-xs text-slate-300">Consulte, corrija e acompanhe cada profissional carregado pelas planilhas.</p></div><div><label className="block text-xs text-slate-300">Competência inicial</label><input type="month" className="mt-1 rounded-lg bg-slate-800 px-3 py-2 text-sm" value={inicio} onChange={e=>setInicio(e.target.value)}/></div><div><label className="block text-xs text-slate-300">Competência final</label><input type="month" min={inicio} className="mt-1 rounded-lg bg-slate-800 px-3 py-2 text-sm" value={fim} onChange={e=>setFim(e.target.value<inicio?inicio:e.target.value)}/></div><div className="min-w-48"><label className="block text-xs text-slate-300">Empresa</label><select className="mt-1 w-full rounded-lg bg-slate-800 px-3 py-2 text-sm" value={empresaId} onChange={e=>setEmpresaId(e.target.value)}><option value="">Todas</option>{empresas.map(e=><option key={e.id} value={e.id}>{e.apelido||e.razao_social}</option>)}</select></div><button className="rounded-lg border border-slate-600 px-3 py-2 text-sm disabled:opacity-50" disabled={loading} onClick={carregar}>{loading?'Atualizando…':'Atualizar'}</button></div></section>
  <section className="grid grid-cols-2 gap-2 md:grid-cols-4"><Stat label="Importados" valor={String(totais.total)}/><Stat label="Com nota" valor={String(totais.comNota)} tom="verde"/><Stat label="Sem nota" valor={String(totais.semNota)} tom="amarelo"/><Stat label="Valor importado" valor={formatarMoeda(totais.valor)}/></section>
  <section className="rounded-xl border bg-white p-3 shadow-sm"><div className="grid gap-3 md:grid-cols-[1fr_220px]"><div><label className="label-field">Buscar profissional, CNPJ, empresa ou nota</label><input type="search" className="input-field" value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Digite para filtrar"/></div><div><label className="label-field">Situação</label><select className="input-field" value={status} onChange={e=>setStatus(e.target.value as Status)}><option value="todos">Todos</option><option value="com_nota">Com nota</option><option value="sem_nota">Sem nota</option><option value="divergentes">Valor divergente</option><option value="analise">Em análise</option></select></div></div></section>
  {selecionada&&<section className="rounded-xl border border-blue-200 bg-blue-50/50 p-4"><div className="mb-3 flex justify-between"><div><h2 className="font-semibold">Editar dado importado</h2><p className="text-xs text-gray-500">Alterações incompatíveis desfazem o vínculo automaticamente.</p></div><button onClick={()=>setSelecionada(null)}>×</button></div><div className="grid gap-3 md:grid-cols-5"><Campo label="Nome" valor={form.nome} set={v=>setForm({...form,nome:v})}/><Campo label="CPF/CNPJ" valor={form.documento} set={v=>setForm({...form,documento:v})}/><Campo label="Competência" tipo="month" valor={form.mes_ref} set={v=>setForm({...form,mes_ref:v})}/><Campo label="Valor" valor={form.valor_comissao} set={v=>setForm({...form,valor_comissao:v})}/><Campo label="Observação" valor={form.observacao} set={v=>setForm({...form,observacao:v})}/></div><div className="mt-3 flex justify-end gap-2"><button className="btn-secondary" onClick={()=>setSelecionada(null)}>Cancelar</button><button className="btn-primary" disabled={!!acao} onClick={salvar}>{acao==='salvar'?'Salvando…':'Salvar e reavaliar'}</button></div></section>}
  <section className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b p-3"><div><h2 className="font-semibold">Profissionais importados</h2><p className="text-xs text-gray-500">{filtradas.length} registro(s) no período</p></div><span className="text-xs text-gray-400">Página {pagina} de {totalPag}</span></div>{loading?<div className="py-14 text-center text-sm text-gray-400">Carregando dados…</div>:visiveis.length===0?<div className="py-14 text-center text-sm text-gray-500">Nenhum dado importado encontrado com estes filtros.</div>:<div className="overflow-x-auto"><table className="w-full"><thead><tr className="bg-gray-50"><th className="table-header">Empresa</th><th className="table-header">Profissional</th><th className="table-header">CPF/CNPJ</th><th className="table-header">Competência</th><th className="table-header text-right">Valor</th><th className="table-header">Nota vinculada</th><th className="table-header">Situação</th><th className="table-header text-right">Gestão</th></tr></thead><tbody className="divide-y">{visiveis.map(l=><tr key={l.id} className="hover:bg-slate-50"><td className="table-cell text-xs">{l.empresaNome}</td><td className="table-cell font-medium">{l.nome||'—'}</td><td className="table-cell text-xs">{l.documento||'—'}</td><td className="table-cell">{l.mes_ref}</td><td className="table-cell text-right">{formatarMoeda(l.valor_comissao||0)}</td><td className="table-cell">{l.nf_numero||'—'}</td><td className="table-cell"><span className={`rounded-full px-2 py-1 text-xs ${l.nota_id?'bg-emerald-100 text-emerald-700':'bg-amber-100 text-amber-800'}`}>{SITUACAO_LABEL[l.situacao]||l.situacao}</span></td><td className="table-cell text-right whitespace-nowrap"><button className="mr-3 text-xs font-semibold text-blue-700" onClick={()=>editar(l)}>Editar</button><button className="mr-3 text-xs font-semibold text-slate-600" onClick={()=>analisar(l)}>Analisar</button>{l.nota_id&&<button className="mr-3 text-xs font-semibold text-amber-700" onClick={()=>removerVinculo(l)}>Desvincular</button>}<button className="text-xs font-semibold text-red-600" onClick={()=>excluir(l)}>Excluir</button></td></tr>)}</tbody></table></div>}<div className="flex justify-end gap-2 border-t p-3"><button className="btn-secondary text-sm" disabled={pagina===1} onClick={()=>setPagina(p=>p-1)}>Anterior</button><button className="btn-secondary text-sm" disabled={pagina>=totalPag} onClick={()=>setPagina(p=>p+1)}>Próxima</button></div></section>
 </div></LayoutAdmin>
}
function Stat({label,valor,tom='azul'}:{label:string;valor:string;tom?:'azul'|'verde'|'amarelo'}){const cor={azul:'text-slate-900',verde:'text-emerald-700',amarelo:'text-amber-700'}[tom];return <div className="rounded-xl border bg-white p-3 shadow-sm"><span className="text-xs text-gray-500">{label}</span><b className={`block text-xl ${cor}`}>{valor}</b></div>}
function Campo({label,valor,set,tipo='text'}:{label:string;valor:string;set:(v:string)=>void;tipo?:string}){return <div><label className="label-field">{label}</label><input type={tipo} className="input-field" value={valor} onChange={e=>set(e.target.value)}/></div>}
