'use client'
import { useCallback,useDeferredValue,useEffect,useMemo,useState } from 'react'
import { useRouter } from 'next/navigation'
import LayoutAdmin from '../../../components/LayoutAdmin'
import { supabase,type Empresa } from '../../../lib/supabase'
import { SALAO_ENABLED } from '../../../lib/salao/config'
import { consultarConferencia,vincularNota,editarNota,editarComissao,classificarNota,excluirNota,setAnaliseManual,SITUACAO_LABEL,type LinhaConsulta } from '../../../lib/salao/conferencia'
import { formatarMoeda } from '../../../utils/calculoVT'
function mesAtual(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}function mesesEntre(a:string,b:string){const out:string[]=[];let[y,m]=a.split('-').map(Number);const[fy,fm]=b.split('-').map(Number);while(y*12+m<=fy*12+fm&&out.length<24){out.push(`${y}-${String(m).padStart(2,'0')}`);m++;if(m>12){m=1;y++}}return out}
type NotaUI={id:string;nome:string;documento:string|null;numero:string|null;data:string|null;valor:number|null;competencia:string;situacao:string;analise?:boolean}
type AbaNota='todas'|'pendentes'|'sem_profissional'|'divergentes'|'conferidas';type AbaPro='todos'|'sem_nota'|'sugestao'|'divergentes'|'conferidos'
export default function ConferenciaPage(){const router=useRouter();const[empresas,setEmpresas]=useState<Empresa[]>([]);const[empresaId,setEmpresaId]=useState('');const[inicio,setInicio]=useState(mesAtual());const[fim,setFim]=useState(mesAtual());const[profissional,setProfissional]=useState('');const[linhas,setLinhas]=useState<LinhaConsulta[]>([]);const[loading,setLoading]=useState(false);const[msg,setMsg]=useState('');const[notaSel,setNotaSel]=useState<NotaUI|null>(null);const[proSel,setProSel]=useState<LinhaConsulta|null>(null);const[abaN,setAbaN]=useState<AbaNota>('pendentes');const[abaP,setAbaP]=useState<AbaPro>('sem_nota');const[buscaN,setBuscaN]=useState('');const[buscaP,setBuscaP]=useState('');const[editor,setEditor]=useState<'nota'|'pro'|null>(null);const[form,setForm]=useState<Record<string,string>>({});const[usuario,setUsuario]=useState<string|undefined>()
useEffect(()=>{if(!SALAO_ENABLED){router.replace('/dashboard');return}supabase.from('empresas').select('*').order('razao_social').then(({data})=>setEmpresas(data||[]));supabase.auth.getUser().then(({data})=>setUsuario(data.user?.email))},[router])
const carregar=useCallback(async()=>{setLoading(true);const rs=await Promise.all(mesesEntre(inicio,fim).map(competencia=>consultarConferencia({competencia,empresaId:empresaId||undefined},{campo:'nome',dir:'asc'},1,500)));setLinhas(rs.flatMap(r=>r.linhas));setLoading(false)},[inicio,fim,empresaId]);useEffect(()=>{if(SALAO_ENABLED)carregar()},[carregar])
const buscaNDebounced=useDeferredValue(buscaN);const buscaPDebounced=useDeferredValue(buscaP)
const profissionais=useMemo(()=>linhas.filter(l=>l.tipo==='comissao'),[linhas]);const nomes=useMemo(()=>Array.from(new Set(profissionais.map(l=>l.nome||'').filter(Boolean))).sort(),[profissionais])
const notas=useMemo<NotaUI[]>(()=>{const m=new Map<string,NotaUI>();for(const l of linhas){const id=l.tipo==='nota'?l.id:l.nota_id;if(!id)continue;m.set(id,{id,nome:l.tipo==='nota'?(l.nome||'Emitente não identificado'):(l.nome||'Profissional'),documento:l.documento,numero:l.nf_numero,data:l.nf_data,valor:l.nf_valor,competencia:l.nota_competencia||l.mes_ref,situacao:l.situacao})}return [...m.values()]},[linhas])
const notasVis=useMemo(()=>notas.filter(n=>(!profissional||n.nome.toLowerCase().includes(profissional.toLowerCase()))&&(!buscaNDebounced||(`${n.nome} ${n.documento} ${n.numero}`).toLowerCase().includes(buscaNDebounced.toLowerCase()))&&(abaN==='todas'||abaN==='pendentes'&&n.situacao!=='conferido'||abaN==='sem_profissional'&&n.situacao==='nota_sem_vinculo'||abaN==='divergentes'&&n.situacao.includes('divergencia')||abaN==='conferidas'&&n.situacao==='conferido')),[notas,profissional,buscaNDebounced,abaN])
const prosVis=useMemo(()=>profissionais.filter(p=>(!profissional||p.nome===profissional)&&(!buscaPDebounced||(`${p.nome} ${p.documento}`).toLowerCase().includes(buscaPDebounced.toLowerCase()))&&(abaP==='todos'||abaP==='sem_nota'&&!p.nota_id||abaP==='sugestao'&&!!p.sugestaoNotaId||abaP==='divergentes'&&p.situacao==='divergencia_valor'||abaP==='conferidos'&&p.situacao==='conferido')),[profissionais,profissional,buscaPDebounced,abaP])
async function vincular(){if(!notaSel||!proSel)return;const r=await vincularNota(proSel.id,{id:notaSel.id,numero:notaSel.numero,valor:notaSel.valor,data_emissao:notaSel.data});if(!r.ok){setMsg(r.erro||'Erro.');return}setMsg('Nota vinculada. Os dois registros saíram das pendências.');setNotaSel(null);setProSel(null);carregar()}
function editarN(n=notaSel){if(!n)return;setNotaSel(n);setEditor('nota');setForm({emitente_nome:n.nome,documento:n.documento||'',numero:n.numero||'',data_emissao:n.data||'',competencia:n.competencia,valor:String(n.valor||'')})}function editarP(){if(!proSel)return;setEditor('pro');setForm({nome:proSel.nome||'',documento:proSel.documento||'',mes_ref:proSel.mes_ref,valor_comissao:String(proSel.valor_comissao||'')})}
async function salvar(){if(editor==='nota'&&notaSel)await editarNota(notaSel.id,form,usuario);if(editor==='pro'&&proSel)await editarComissao(proSel.id,form,usuario);setEditor(null);setMsg('Dados atualizados e vínculos reavaliados.');carregar()}
async function outro(n=notaSel){if(!n)return;setLinhas(v=>v.filter(l=>(l.tipo==='nota'?l.id:l.nota_id)!==n.id));setNotaSel(null);const r=await classificarNota(n.id,'outro_servico',{categoria:'Outro serviço',observacao:'Classificação rápida pela conferência',usuario});if(!r.ok){setMsg(r.erro||'Erro ao classificar.');carregar();return}setMsg('Nota movida para Outros serviços em um clique.')}async function excluir(n=notaSel){if(!n)return;setLinhas(v=>v.filter(l=>(l.tipo==='nota'?l.id:l.nota_id)!==n.id));setNotaSel(null);const r=await excluirNota(n.id,'Exclusão rápida pela conferência',usuario);if(!r.ok){setMsg(r.erro||'Erro ao excluir.');carregar();return}setMsg('Nota removida. A ação fica registrada e pode ser restaurada.')}async function analisar(tipo:'nota'|'comissao',id:string){await setAnaliseManual(tipo,id,true,'Analisar posteriormente',usuario);setMsg('Registro enviado para análise posterior.');carregar()}
if(!SALAO_ENABLED)return null;return <LayoutAdmin title="Salão — Conferência"><div className="space-y-3">{msg&&<div className="rounded-lg border border-blue-200 bg-blue-50 p-3 text-sm text-blue-800">{msg}</div>}<section className="rounded-xl bg-slate-900 p-4 text-white"><div className="flex flex-wrap items-end gap-3"><div className="mr-auto"><h1 className="text-lg font-semibold">Conferência de NFS-e</h1><p className="text-xs text-slate-300">Selecione uma nota e um profissional para vincular.</p></div><div><label className="block text-xs text-slate-300">Mês inicial</label><input type="month" className="mt-1 rounded-lg bg-slate-800 px-3 py-2 text-sm" value={inicio} onChange={e=>setInicio(e.target.value)}/></div><div><label className="block text-xs text-slate-300">Mês final</label><input type="month" className="mt-1 rounded-lg bg-slate-800 px-3 py-2 text-sm" value={fim} min={inicio} onChange={e=>setFim(e.target.value<inicio?inicio:e.target.value)}/></div><div><label className="block text-xs text-slate-300">Empresa</label><select className="mt-1 rounded-lg bg-slate-800 px-3 py-2 text-sm" value={empresaId} onChange={e=>setEmpresaId(e.target.value)}><option value="">Todas</option>{empresas.map(e=><option key={e.id} value={e.id}>{e.apelido||e.razao_social}</option>)}</select></div><div><label className="block text-xs text-slate-300">Profissional do período</label><select className="mt-1 min-w-48 rounded-lg bg-slate-800 px-3 py-2 text-sm" value={profissional} onChange={e=>setProfissional(e.target.value)}><option value="">Todos</option>{nomes.map(n=><option key={n}>{n}</option>)}</select></div></div><div className="mt-3 flex flex-wrap gap-4 text-xs text-slate-300"><span><b className="text-white">{notas.length}</b> notas</span><span><b className="text-white">{profissionais.length}</b> profissionais</span><span><b className="text-white">{profissionais.filter(p=>p.situacao==='conferido').length}</b> vinculados</span></div></section>
<div className="grid gap-3 xl:grid-cols-2"><Frame titulo="Notas baixadas" subtitulo={`${notasVis.length} visíveis`} abas={[['todas','Todas'],['pendentes','Pendentes'],['sem_profissional','Sem profissional'],['divergentes','Divergentes'],['conferidas','Conferidas']]} ativa={abaN} setAtiva={v=>setAbaN(v as AbaNota)} busca={buscaN} setBusca={setBuscaN}>{loading?<Loading/>:notasVis.map(n=><div key={n.id} role="button" tabIndex={0} onClick={()=>setNotaSel(n)} className={`mb-1 w-full rounded-lg border p-3 text-left transition ${notaSel?.id===n.id?'border-blue-500 bg-blue-50 shadow-sm':'border-transparent hover:bg-gray-50'}`}><div className="flex justify-between gap-2 text-sm font-medium"><span>{n.nome}</span><span>{formatarMoeda(n.valor||0)}</span></div><div className="mt-1 flex justify-between text-xs text-gray-500"><span>{n.documento||'—'} · NF {n.numero||'—'}</span><span>{SITUACAO_LABEL[n.situacao as keyof typeof SITUACAO_LABEL]||n.situacao}</span></div><div className="mt-2 flex justify-end gap-2 border-t pt-2"><button onClick={e=>{e.stopPropagation();editarN(n)}} className="text-xs font-medium text-blue-700">Editar</button><button onClick={e=>{e.stopPropagation();outro(n)}} className="text-xs font-medium text-amber-700">Outro serviço</button><button onClick={e=>{e.stopPropagation();excluir(n)}} className="text-xs font-medium text-red-600">Excluir</button></div></div>)}</Frame>
<Frame titulo="Profissionais importados" subtitulo={`${prosVis.length} visíveis`} abas={[['todos','Todos'],['sem_nota','Sem nota'],['sugestao','Com sugestão'],['divergentes','Divergentes'],['conferidos','Conferidos']]} ativa={abaP} setAtiva={v=>setAbaP(v as AbaPro)} busca={buscaP} setBusca={setBuscaP}>{loading?<Loading/>:prosVis.map(p=><button key={p.id} onClick={()=>setProSel(p)} className={`mb-1 w-full rounded-lg border p-3 text-left ${proSel?.id===p.id?'border-blue-500 bg-blue-50':'border-transparent hover:bg-gray-50'}`}><div className="flex justify-between gap-2 text-sm font-medium"><span>{p.nome}</span><span>{formatarMoeda(p.valor_comissao||0)}</span></div><div className="mt-1 flex justify-between text-xs text-gray-500"><span>{p.documento||'—'} · {p.mes_ref}</span><span>{p.nota_id?'Com nota':'Sem nota'}</span></div></button>)}</Frame></div>
<section className="rounded-xl border bg-white p-3 shadow-sm">{notaSel&&proSel?<><div className="grid items-center gap-2 md:grid-cols-[1fr_auto_1fr]"><Resumo rotulo="Nota selecionada" nome={notaSel.nome} detalhe={`${notaSel.numero||'—'} · ${formatarMoeda(notaSel.valor||0)} · ${notaSel.competencia}`}/><span className="text-blue-600">⇄</span><Resumo rotulo="Profissional selecionado" nome={proSel.nome||'—'} detalhe={`${formatarMoeda(proSel.valor_comissao||0)} · ${proSel.mes_ref}`}/></div><div className="mt-3 flex flex-wrap gap-2"><button className="btn-primary" onClick={vincular}>Vincular nota</button><button className="btn-secondary" onClick={editarN}>Editar nota</button><button className="btn-secondary" onClick={editarP}>Editar profissional</button><button className="btn-secondary text-amber-700" onClick={()=>outro()}>Outro serviço</button><button className="btn-secondary" onClick={()=>analisar('nota',notaSel.id)}>Analisar depois</button><button className="btn-secondary text-red-600" onClick={()=>excluir()}>Excluir nota</button></div></>:<p className="text-center text-sm text-gray-500">Selecione uma nota e um profissional. As ações de cada lado ficam disponíveis aqui.</p>}</section>
{editor&&<section className="rounded-xl border border-blue-200 bg-white p-4"><div className="grid gap-3 md:grid-cols-4">{Object.entries(form).map(([k,v])=><div key={k}><label className="label-field">{k.replaceAll('_',' ')}</label><input className="input-field" value={v} onChange={e=>setForm({...form,[k]:e.target.value})}/></div>)}</div><div className="mt-3 flex justify-end gap-2"><button className="btn-secondary" onClick={()=>setEditor(null)}>Cancelar</button><button className="btn-primary" onClick={salvar}>Salvar e reavaliar</button></div></section>}</div></LayoutAdmin>}
function Frame(p:{titulo:string;subtitulo:string;abas:string[][];ativa:string;setAtiva:(v:string)=>void;busca:string;setBusca:(v:string)=>void;children:React.ReactNode}){return <section className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="flex justify-between border-b p-3"><h2 className="font-semibold">{p.titulo}</h2><span className="text-xs text-gray-500">{p.subtitulo}</span></div><div className="flex gap-1 overflow-x-auto border-b p-2">{p.abas.map(([k,l])=><button key={k} onClick={()=>p.setAtiva(k)} className={`whitespace-nowrap rounded-full border px-2 py-1 text-xs ${p.ativa===k?'bg-slate-900 text-white':''}`}>{l}</button>)}</div><div className="border-b p-2"><input className="input-field" placeholder="Buscar neste quadro" value={p.busca} onChange={e=>p.setBusca(e.target.value)}/></div><div className="h-80 overflow-y-auto p-2">{p.children}</div></section>}
function Resumo({rotulo,nome,detalhe}:{rotulo:string;nome:string;detalhe:string}){return <div className="rounded-lg bg-gray-50 p-3"><span className="text-xs text-gray-500">{rotulo}</span><b className="block text-sm">{nome}</b><span className="text-xs text-gray-500">{detalhe}</span></div>}function Loading(){return <div className="py-10 text-center text-sm text-gray-400">Carregando...</div>}
