'use client'
import { useCallback,useDeferredValue,useEffect,useMemo,useRef,useState } from 'react'
import { useRouter } from 'next/navigation'
import LayoutAdmin from '../../../components/LayoutAdmin'
import { supabase,type Empresa } from '../../../lib/supabase'
import { SALAO_ENABLED } from '../../../lib/salao/config'
import { consultarConferencia,vincularNota,desvincular,editarNota,editarComissao,excluirComissao,classificarNota,excluirNota,setAnaliseManual,setNotaConferida,SITUACAO_LABEL,type LinhaConsulta } from '../../../lib/salao/conferencia'
import { formatarMoeda } from '../../../utils/calculoVT'
function mesAtual(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}function mesesEntre(a:string,b:string){const out:string[]=[];let[y,m]=a.split('-').map(Number);const[fy,fm]=b.split('-').map(Number);while(y*12+m<=fy*12+fm&&out.length<24){out.push(`${y}-${String(m).padStart(2,'0')}`);m++;if(m>12){m=1;y++}}return out}
type NotaUI={id:string;nome:string;documento:string|null;numero:string|null;data:string|null;valor:number|null;competencia:string;situacao:string;analise?:boolean;conferida?:boolean}
type AbaNota='todas'|'pendentes'|'sem_profissional'|'divergentes'|'conferidas';type AbaPro='todos'|'sem_nota'|'sugestao'|'divergentes'|'conferidos'
export default function ConferenciaPage(){const router=useRouter();const[empresas,setEmpresas]=useState<Empresa[]>([]);const[empresaId,setEmpresaId]=useState('');const[inicio,setInicio]=useState(mesAtual());const[fim,setFim]=useState(mesAtual());const[profissional,setProfissional]=useState('');const[linhas,setLinhas]=useState<LinhaConsulta[]>([]);const[loading,setLoading]=useState(false);const[msg,setMsg]=useState('');const[notaSel,setNotaSel]=useState<NotaUI|null>(null);const[proSel,setProSel]=useState<LinhaConsulta|null>(null);const[abaN,setAbaN]=useState<AbaNota>('pendentes');const[abaP,setAbaP]=useState<AbaPro>('sem_nota');const[buscaN,setBuscaN]=useState('');const[buscaP,setBuscaP]=useState('');const[editor,setEditor]=useState<'nota'|'pro'|null>(null);const[form,setForm]=useState<Record<string,string>>({});const[usuario,setUsuario]=useState<string|undefined>();const requisicao=useRef(0);const[acao,setAcao]=useState('')
useEffect(()=>{if(!SALAO_ENABLED){router.replace('/dashboard');return}supabase.from('empresas').select('*').order('razao_social').then(({data})=>setEmpresas(data||[]));supabase.auth.getUser().then(({data})=>setUsuario(data.user?.email))},[router])
const carregar=useCallback(async()=>{const id=++requisicao.current;setLoading(true);try{const rs=await Promise.all(mesesEntre(inicio,fim).map(competencia=>consultarConferencia({competencia,empresaId:empresaId||undefined},{campo:'nome',dir:'asc'},1,500)));if(id===requisicao.current)setLinhas(rs.flatMap(r=>r.linhas))}catch(e){if(id===requisicao.current)setMsg(e instanceof Error?e.message:'Erro ao carregar a conferência.')}finally{if(id===requisicao.current)setLoading(false)}},[inicio,fim,empresaId]);useEffect(()=>{if(SALAO_ENABLED)carregar()},[carregar])
const buscaNDebounced=useDeferredValue(buscaN);const buscaPDebounced=useDeferredValue(buscaP)
const profissionais=useMemo(()=>linhas.filter(l=>l.tipo==='comissao'&&(!empresaId||l.empresa_id===empresaId)),[linhas,empresaId]);const nomes=useMemo(()=>Array.from(new Set(profissionais.map(l=>l.nome||'').filter(Boolean))).sort(),[profissionais])
const notas=useMemo<NotaUI[]>(()=>{const m=new Map<string,NotaUI>();for(const l of linhas){if(empresaId&&l.empresa_id!==empresaId)continue;const id=l.tipo==='nota'?l.id:l.nota_id;if(!id)continue;m.set(id,{id,nome:l.tipo==='nota'?(l.nome||'Emitente não identificado'):(l.nome||'Profissional'),documento:l.documento,numero:l.nf_numero,data:l.nf_data,valor:l.nf_valor,competencia:l.nota_competencia||l.mes_ref,situacao:l.situacao,conferida:l.conferida??l.situacao==='conferido'})}return [...m.values()]},[linhas,empresaId])
const notasVis=useMemo(()=>notas.filter(n=>{if(profissional&&!n.nome.toLowerCase().includes(profissional.toLowerCase()))return false;if(buscaNDebounced&&!(`${n.nome} ${n.documento} ${n.numero}`).toLowerCase().includes(buscaNDebounced.toLowerCase()))return false;switch(abaN){case'pendentes':return n.situacao!=='conferido'&&n.situacao!=='corrigido_manual';case'sem_profissional':return n.situacao==='nota_sem_vinculo';case'divergentes':return n.situacao==='divergencia_valor'||n.situacao==='nota_outra_empresa';case'conferidas':return n.situacao==='conferido'||n.situacao==='corrigido_manual';default:return true}}),[notas,profissional,buscaNDebounced,abaN])
const prosVis=useMemo(()=>profissionais.filter(p=>{if(profissional&&p.nome!==profissional)return false;if(buscaPDebounced&&!(`${p.nome} ${p.documento} ${p.nf_numero}`).toLowerCase().includes(buscaPDebounced.toLowerCase()))return false;switch(abaP){case'sem_nota':return !p.nota_id;case'sugestao':return !!p.sugestaoNotaId;case'divergentes':return p.situacao==='divergencia_valor'||p.situacao==='nota_outra_empresa';case'conferidos':return p.situacao==='conferido'||p.situacao==='corrigido_manual';default:return true}}),[profissionais,profissional,buscaPDebounced,abaP])
async function vincular(){if(!notaSel||!proSel||acao)return;setAcao('vincular');const notaId=notaSel.id,proId=proSel.id;const r=await vincularNota(proId,{id:notaId,numero:notaSel.numero,valor:notaSel.valor,data_emissao:notaSel.data},usuario);if(!r.ok){setMsg(r.erro||'Erro.');setAcao('');return}setLinhas(v=>v.filter(l=>!(l.tipo==='nota'&&l.id===notaId)).map(l=>l.id===proId?{...l,nota_id:notaId,situacao:'conferido'}:l));setMsg('Vínculo concluído e marcado como conferido.');setNotaSel(null);setProSel(null);setAbaN('pendentes');setAbaP('sem_nota');void carregar();setAcao('')}
function editarN(n=notaSel){if(!n)return;setNotaSel(n);setEditor('nota');setForm({emitente_nome:n.nome,documento:n.documento||'',numero:n.numero||'',data_emissao:n.data||'',competencia:n.competencia,valor:String(n.valor||'')})}function editarP(p=proSel){if(!p)return;setProSel(p);setEditor('pro');setForm({nome:p.nome||'',documento:p.documento||'',mes_ref:p.mes_ref,valor_comissao:String(p.valor_comissao||'')})}
async function salvar(){if(editor==='nota'&&notaSel)await editarNota(notaSel.id,form,usuario);if(editor==='pro'&&proSel)await editarComissao(proSel.id,form,usuario);setEditor(null);setMsg('Dados atualizados e vínculos reavaliados.');carregar()}
async function conferir(n=notaSel){if(!n||acao)return;setAcao('conferir');const proximo=!n.conferida;setNotaSel({...n,conferida:proximo,situacao:proximo?'conferido':'nota_sem_vinculo'});setLinhas(v=>v.map(l=>(l.tipo==='nota'&&l.id===n.id)?{...l,conferida:proximo,situacao:proximo?'conferido':'nota_sem_vinculo'}:l));const r=await setNotaConferida(n.id,proximo,usuario);if(!r.ok){setMsg(r.erro||'Erro ao conferir.');carregar();setAcao('');return}setMsg(proximo?'Nota marcada como conferida.':'Nota reaberta para conferência.');setAcao('')}
async function outro(n=notaSel){if(!n||acao)return;setAcao('outro');setLinhas(v=>v.filter(l=>(l.tipo==='nota'?l.id:l.nota_id)!==n.id));setNotaSel(null);const r=await classificarNota(n.id,'outro_servico',{categoria:'Outro serviço',observacao:'Classificação rápida pela conferência',usuario});if(!r.ok){setMsg(r.erro||'Erro ao classificar.');carregar();setAcao('');return}setMsg('Nota movida para Outros serviços em um clique.');setAcao('')}async function excluir(n=notaSel){if(!n||acao)return;setAcao('excluir');setLinhas(v=>v.filter(l=>(l.tipo==='nota'?l.id:l.nota_id)!==n.id));setNotaSel(null);const r=await excluirNota(n.id,'Exclusão rápida pela conferência',usuario);if(!r.ok){setMsg(r.erro||'Erro ao excluir.');carregar();setAcao('');return}setMsg('Nota removida. A ação fica registrada e pode ser restaurada.');setAcao('')}async function desvincularP(p=proSel){if(!p?.nota_id||acao)return;setAcao('desvincular');const r=await desvincular(p.id,p.nota_id);if(!r.ok){setMsg(r.erro||'Erro ao desvincular.');setAcao('');return}setMsg('Vínculo removido. Nota e profissional voltaram para análise.');setProSel(null);await carregar();setAcao('')}
async function excluirP(p=proSel){if(!p||acao)return;setAcao('excluir-pro');setLinhas(v=>v.filter(l=>l.id!==p.id));setProSel(null);const r=await excluirComissao(p.id,usuario);setAcao('');if(!r.ok){setMsg(r.erro||'Erro ao excluir profissional.');carregar();return}setMsg('Profissional removido dos dados importados. A ação foi registrada na auditoria.')}
async function analisar(tipo:'nota'|'comissao',id:string){await setAnaliseManual(tipo,id,true,'Analisar posteriormente',usuario);setMsg('Registro enviado para análise posterior.');carregar()}
const primeiraCarga=loading&&linhas.length===0
if(!SALAO_ENABLED)return null;return <LayoutAdmin title="Salão — Conferência"><div className="space-y-3">{msg&&<div className="rounded-lg border border-blue-200 bg-blue-50 p-3 text-sm text-blue-800">{msg}</div>}<section className="rounded-xl bg-slate-900 p-4 text-white"><div className="flex flex-wrap items-end gap-3"><div className="mr-auto"><h1 className="text-lg font-semibold">Conferência de NFS-e</h1><p className="text-xs text-slate-300">Selecione uma nota e um profissional para vincular.</p></div><div><label className="block text-xs text-slate-300">Mês inicial</label><input type="month" className="mt-1 rounded-lg bg-slate-800 px-3 py-2 text-sm" value={inicio} onChange={e=>setInicio(e.target.value)}/></div><div><label className="block text-xs text-slate-300">Mês final</label><input type="month" className="mt-1 rounded-lg bg-slate-800 px-3 py-2 text-sm" value={fim} min={inicio} onChange={e=>setFim(e.target.value<inicio?inicio:e.target.value)}/></div><div><label className="block text-xs text-slate-300">Empresa</label><select className="mt-1 rounded-lg bg-slate-800 px-3 py-2 text-sm" value={empresaId} onChange={e=>setEmpresaId(e.target.value)}><option value="">Todas</option>{empresas.map(e=><option key={e.id} value={e.id}>{e.apelido||e.razao_social}</option>)}</select></div><div><label className="block text-xs text-slate-300">Profissional do período</label><select className="mt-1 min-w-48 rounded-lg bg-slate-800 px-3 py-2 text-sm" value={profissional} onChange={e=>setProfissional(e.target.value)}><option value="">Todos</option>{nomes.map(n=><option key={n}>{n}</option>)}</select></div></div>{loading&&linhas.length>0&&<div className="mt-3 text-xs font-medium text-blue-300">Atualizando filtros em segundo plano…</div>}<div className="mt-3 flex flex-wrap gap-4 text-xs text-slate-300"><span><b className="text-white">{notas.length}</b> notas</span><span><b className="text-white">{profissionais.length}</b> profissionais</span><span><b className="text-white">{profissionais.filter(p=>p.situacao==='conferido').length}</b> vinculados</span></div></section>
<section className="rounded-2xl border border-slate-200 bg-slate-100/70 p-3 shadow-sm">
 <div className="mb-3 flex items-center justify-between"><div><h2 className="text-sm font-semibold text-slate-900">Área de gestão</h2><p className="text-xs text-slate-500">Selecione registros nos quadros e execute a ação sem sair da conferência.</p></div>{(notaSel||proSel)&&<button className="text-xs font-medium text-slate-500 hover:text-slate-900" onClick={()=>{setNotaSel(null);setProSel(null)}}>Limpar seleção</button>}</div>
 <div className="grid gap-3 lg:grid-cols-2">
  <div className={`rounded-xl border bg-white p-3 ${notaSel?'border-blue-300 shadow-sm':'border-dashed border-slate-300'}`}>{notaSel?<><Resumo rotulo="Gestão da nota" nome={notaSel.nome} detalhe={`NF ${notaSel.numero||'—'} · ${formatarMoeda(notaSel.valor||0)} · ${notaSel.competencia}`}/><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3"><Acao label={notaSel.conferida?'Reabrir nota':'Conferir nota'} tom="verde" onClick={()=>conferir()}/><Acao label="Editar dados" tom="azul" onClick={()=>editarN()}/><Acao label="Analisar depois" onClick={()=>analisar('nota',notaSel.id)}/><Acao label="Outro serviço" tom="amarelo" onClick={()=>outro()}/><Acao label="Excluir nota" tom="vermelho" onClick={()=>excluir()}/></div></>:<Selecione texto="Selecione uma nota no quadro esquerdo"/>}</div>
  <div className={`rounded-xl border bg-white p-3 ${proSel?'border-violet-300 shadow-sm':'border-dashed border-slate-300'}`}>{proSel?<><Resumo rotulo="Gestão do profissional importado" nome={proSel.nome||'—'} detalhe={`${formatarMoeda(proSel.valor_comissao||0)} · ${proSel.mes_ref} · ${proSel.nota_id?'Com nota':'Sem nota'}`}/><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3"><Acao label="Editar dados" tom="azul" onClick={()=>editarP()}/><Acao label="Analisar depois" onClick={()=>analisar('comissao',proSel.id)}/>{proSel.nota_id&&<Acao label="Desvincular nota" tom="amarelo" onClick={()=>desvincularP()}/>}<Acao label="Excluir importado" tom="vermelho" onClick={()=>excluirP()}/></div></>:<Selecione texto="Selecione um profissional no quadro direito"/>}</div>
 </div>
 {notaSel&&proSel&&<button className="mt-3 w-full rounded-xl bg-blue-600 px-4 py-3 text-sm font-bold text-white shadow-sm transition hover:bg-blue-500 disabled:opacity-50" disabled={!!acao} onClick={vincular}>{acao==='vincular'?'Vinculando…':'Vincular nota ao profissional e conferir'}</button>}
</section>
<div className="grid gap-3 xl:grid-cols-2"><Frame titulo="Notas baixadas" subtitulo={`${notasVis.length} visíveis`} abas={[['todas','Todas'],['pendentes','Pendentes'],['sem_profissional','Sem profissional'],['divergentes','Divergentes'],['conferidas','Conferidas']]} ativa={abaN} setAtiva={v=>setAbaN(v as AbaNota)} busca={buscaN} setBusca={setBuscaN}>{primeiraCarga?<Loading/>:notasVis.map(n=><div key={n.id} role="button" tabIndex={0} onClick={()=>setNotaSel(n)} className={`mb-1 w-full rounded-lg border p-3 text-left transition ${notaSel?.id===n.id?'border-blue-500 bg-blue-50 shadow-sm':'border-transparent hover:bg-gray-50'}`}><div className="flex justify-between gap-2 text-sm font-medium"><span>{n.nome}</span><span>{formatarMoeda(n.valor||0)}</span></div><div className="mt-1 flex justify-between text-xs text-gray-500"><span>{n.documento||'—'} · NF {n.numero||'—'}</span><span>{SITUACAO_LABEL[n.situacao as keyof typeof SITUACAO_LABEL]||n.situacao}</span></div><div className="mt-2 flex justify-end gap-2 border-t pt-2"><button onClick={e=>{e.stopPropagation();conferir(n)}} className={`rounded-md px-2 py-1 text-xs font-semibold ${n.conferida?'bg-emerald-100 text-emerald-700':'bg-slate-100 text-slate-700'}`}>{n.conferida?'✓ Conferida':'Conferir'}</button><button onClick={e=>{e.stopPropagation();editarN(n)}} className="text-xs font-medium text-blue-700">Editar</button><button onClick={e=>{e.stopPropagation();outro(n)}} className="text-xs font-medium text-amber-700">Outro serviço</button><button onClick={e=>{e.stopPropagation();excluir(n)}} className="text-xs font-medium text-red-600">Excluir</button></div></div>)}</Frame>
<Frame titulo="Profissionais importados" subtitulo={`${prosVis.length} visíveis`} abas={[['todos','Todos'],['sem_nota','Sem nota'],['sugestao','Com sugestão'],['divergentes','Divergentes'],['conferidos','Conferidos']]} ativa={abaP} setAtiva={v=>setAbaP(v as AbaPro)} busca={buscaP} setBusca={setBuscaP}>{primeiraCarga?<Loading/>:prosVis.map(p=><div key={p.id} role="button" tabIndex={0} onClick={()=>setProSel(p)} className={`mb-1 w-full rounded-lg border p-3 text-left transition ${proSel?.id===p.id?'border-violet-400 bg-violet-50 shadow-sm':'border-transparent hover:bg-gray-50'}`}><div className="flex justify-between gap-2 text-sm font-medium"><span>{p.nome}</span><span>{formatarMoeda(p.valor_comissao||0)}</span></div><div className="mt-1 flex justify-between text-xs text-gray-500"><span>{p.documento||'—'} · {p.mes_ref}</span><span>{p.nota_id?'Com nota':'Sem nota'}</span></div><div className="mt-2 flex justify-end gap-3 border-t pt-2"><button onClick={e=>{e.stopPropagation();editarP(p)}} className="text-xs font-medium text-blue-700">Editar</button><button onClick={e=>{e.stopPropagation();analisar('comissao',p.id)}} className="text-xs font-medium text-slate-600">Analisar</button>{p.nota_id&&<button onClick={e=>{e.stopPropagation();desvincularP(p)}} className="text-xs font-medium text-amber-700">Desvincular</button>}<button onClick={e=>{e.stopPropagation();excluirP(p)}} className="text-xs font-medium text-red-600">Excluir</button></div></div>)}</Frame></div>

{editor&&<section className="rounded-xl border border-blue-200 bg-white p-4"><div className="grid gap-3 md:grid-cols-4">{Object.entries(form).map(([k,v])=><div key={k}><label className="label-field">{k.replaceAll('_',' ')}</label><input className="input-field" value={v} onChange={e=>setForm({...form,[k]:e.target.value})}/></div>)}</div><div className="mt-3 flex justify-end gap-2"><button className="btn-secondary" onClick={()=>setEditor(null)}>Cancelar</button><button className="btn-primary" onClick={salvar}>Salvar e reavaliar</button></div></section>}</div></LayoutAdmin>}
function Frame(p:{titulo:string;subtitulo:string;abas:string[][];ativa:string;setAtiva:(v:string)=>void;busca:string;setBusca:(v:string)=>void;children:React.ReactNode}){return <section className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="flex justify-between border-b p-3"><h2 className="font-semibold">{p.titulo}</h2><span className="text-xs text-gray-500">{p.subtitulo}</span></div><div className="flex gap-1 overflow-x-auto border-b p-2">{p.abas.map(([k,l])=><button key={k} onClick={()=>p.setAtiva(k)} className={`whitespace-nowrap rounded-full border px-2 py-1 text-xs ${p.ativa===k?'bg-slate-900 text-white':''}`}>{l}</button>)}</div><div className="border-b p-2"><input className="input-field" placeholder="Buscar neste quadro" value={p.busca} onChange={e=>p.setBusca(e.target.value)}/></div><div className="h-80 overflow-y-auto p-2">{p.children}</div></section>}
function Acao({label,tom='cinza',onClick}:{label:string;tom?:'cinza'|'verde'|'azul'|'amarelo'|'vermelho';onClick:()=>void}){const cls={cinza:'border-slate-200 bg-slate-50 text-slate-700 hover:bg-slate-100',verde:'border-emerald-200 bg-emerald-50 text-emerald-700 hover:bg-emerald-100',azul:'border-blue-200 bg-blue-50 text-blue-700 hover:bg-blue-100',amarelo:'border-amber-200 bg-amber-50 text-amber-800 hover:bg-amber-100',vermelho:'border-red-200 bg-red-50 text-red-700 hover:bg-red-100'}[tom];return <button disabled={false} onClick={onClick} className={`rounded-lg border px-3 py-2 text-xs font-semibold transition ${cls}`}>{label}</button>}
function Selecione({texto}:{texto:string}){return <div className="flex min-h-24 items-center justify-center text-center text-xs text-slate-400">{texto}</div>}
function Resumo({rotulo,nome,detalhe}:{rotulo:string;nome:string;detalhe:string}){return <div className="rounded-lg bg-gray-50 p-3"><span className="text-xs text-gray-500">{rotulo}</span><b className="block text-sm">{nome}</b><span className="text-xs text-gray-500">{detalhe}</span></div>}function Loading(){return <div className="py-10 text-center text-sm text-gray-400">Carregando...</div>}
