'use client'
import { useCallback,useEffect,useMemo,useRef,useState } from 'react'
import { useRouter } from 'next/navigation'
import LayoutAdmin from '../../../components/LayoutAdmin'
import { supabase,type Empresa } from '../../../lib/supabase'
import { SALAO_ENABLED } from '../../../lib/salao/config'
import { consultarConferencia,SITUACAO_LABEL,type Indicadores,type LinhaConsulta,type Situacao } from '../../../lib/salao/conferencia'
import { exportarExcel,exportarPDF,type Coluna } from '../../../lib/salao/relatorios'
import { formatarMoeda,MESES } from '../../../utils/calculoVT'

type Tipo='pendencias'|'conferidos'|'sem_vinculo'|'resumo'
type Row=Omit<Partial<LinhaConsulta>,'situacao'>&{motivo?:string;id?:string;nome?:string|null;documento?:string|null;empresaNome?:string;mes_ref?:string;situacao?:string;nf_valor?:number|null;nf_numero?:string|null;valor_comissao?:number|null;diferenca?:number|null;analise_manual?:boolean}
type Pacote={linhas:Row[];meses:{mes:string;ind:Indicadores}[]}
const TIPOS:{v:Tipo;l:string;d:string}[]=[
 {v:'pendencias',l:'Pendências por profissional',d:'Quem precisa agir e por quê'},
 {v:'conferidos',l:'Conferidos',d:'Entregas concluídas'},
 {v:'sem_vinculo',l:'Sem vínculo',d:'Notas ou profissionais sem par'},
 {v:'resumo',l:'Resumo por competência',d:'Visão executiva mensal'},
]
function mesAtual(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function mesesEntre(a:string,b:string){const out:string[]=[];let[y,m]=a.split('-').map(Number);const[fy,fm]=b.split('-').map(Number);while(y*12+m<=fy*12+fm&&out.length<24){out.push(`${y}-${String(m).padStart(2,'0')}`);m++;if(m>12){m=1;y++}}return out}
function fmtMes(m:string){const[a,mm]=m.split('-').map(Number);return mm?`${MESES[mm-1]}/${a}`:m}
function conferido(s:unknown){return s==='conferido'||s==='conferido_com_divergencia'||s==='corrigido_manual'}
function motivo(r:Row){switch(r.situacao){case'sem_nota':return 'Nota fiscal ainda não localizada';case'nota_sem_vinculo':return 'Nota recebida sem profissional vinculado';case'falta_cnpj':return 'CNPJ/CPF ausente nos dados importados';case'cnpj_invalido':return 'CNPJ/CPF inválido';case'nota_outra_empresa':return 'Nota pertence a outra unidade';case'possivel_duplicidade':return 'Possível registro duplicado';case'vinculo_sugerido':return 'Existe uma nota sugerida aguardando confirmação';case'aguardando_confirmacao':return 'Vínculo precisa de confirmação';case'divergencia_valor':return 'Valor da nota diferente do valor esperado';case'conferido_com_divergencia':return r.observacao||'Conferido com diferença de valor';case'corrigido_manual':return 'Conferido após correção manual';case'conferido':return 'Conferido sem pendências';default:return String(r.situacao||'Revisão necessária')}}

export default function RelatoriosPage(){
 const router=useRouter();const[tipo,setTipo]=useState<Tipo>('pendencias');const[inicio,setInicio]=useState(mesAtual());const[fim,setFim]=useState(mesAtual());const[empresaId,setEmpresaId]=useState('');const[profissional,setProfissional]=useState('');const[situacao,setSituacao]=useState('');const[empresas,setEmpresas]=useState<Empresa[]>([]);const[pacote,setPacote]=useState<Pacote>({linhas:[],meses:[]});const[loading,setLoading]=useState(false);const[erro,setErro]=useState('');const[ordem,setOrdem]=useState<'prioridade'|'nome'|'competencia'|'valor'>('prioridade');const req=useRef(0);const cache=useRef(new Map<string,Pacote>())
 useEffect(()=>{if(!SALAO_ENABLED){router.replace('/dashboard');return}supabase.from('empresas').select('*').order('razao_social').then(({data})=>setEmpresas(data||[]))},[router])
 const carregar=useCallback(async(forcar=false)=>{const chave=`${inicio}|${fim}|${empresaId}`;const salvo=cache.current.get(chave);if(salvo&&!forcar){setPacote(salvo);return}const id=++req.current;setLoading(true);setErro('');try{const meses=mesesEntre(inicio,fim);const rs=await Promise.all(meses.map(competencia=>consultarConferencia({competencia,empresaId:empresaId||undefined},{campo:'nome',dir:'asc'},1,500)));const novo:Pacote={linhas:rs.flatMap(x=>x.linhas),meses:rs.map((x,i)=>({mes:meses[i],ind:x.indicadores}))};cache.current.set(chave,novo);if(id===req.current)setPacote(novo)}catch(e){if(id===req.current)setErro(e instanceof Error?e.message:'Erro ao consultar relatório.')}finally{if(id===req.current)setLoading(false)}},[inicio,fim,empresaId])
 useEffect(()=>{if(SALAO_ENABLED)carregar()},[carregar])
 const profissionais=useMemo(()=>Array.from(new Set(pacote.linhas.filter(l=>l.tipo==='comissao').map(l=>l.nome||'').filter(Boolean))).sort((a,b)=>a.localeCompare(b,'pt-BR')),[pacote.linhas])
 useEffect(()=>{if(profissional&&!profissionais.includes(profissional))setProfissional('')},[profissionais,profissional])
 const indicadores=useMemo(()=>{const b=pacote.linhas;return{total:b.length,pendencias:b.filter(r=>!conferido(r.situacao)).length,semNota:b.filter(r=>r.tipo==='comissao'&&!r.nota_id).length,semProfissional:b.filter(r=>r.tipo==='nota'&&r.situacao==='nota_sem_vinculo').length,divergencias:b.filter(r=>r.situacao==='conferido_com_divergencia'||r.situacao==='divergencia_valor'||r.situacao==='nota_outra_empresa').length}},[pacote.linhas])
 const filtradas=useMemo<Row[]>(()=>{if(tipo==='resumo')return pacote.meses.map(x=>({id:x.mes,nome:fmtMes(x.mes),mes_ref:x.mes,empresaNome:'Todas as unidades',valor_comissao:x.ind.valorEsperado,nf_valor:x.ind.valorVinculado,situacao:`${x.ind.conferidos}/${x.ind.esperados} conferidos`,diferenca:x.ind.diferenca,motivo:x.ind.pendentes?`${x.ind.pendentes} pendência(s)`:'Competência sem pendências'}));let base=[...pacote.linhas];if(tipo==='pendencias')base=base.filter(r=>!conferido(r.situacao));if(tipo==='conferidos')base=base.filter(r=>conferido(r.situacao));if(tipo==='sem_vinculo')base=base.filter(r=>(r.tipo==='comissao'&&!r.nota_id)||(r.tipo==='nota'&&r.situacao==='nota_sem_vinculo'));if(profissional)base=base.filter(r=>r.nome===profissional);if(situacao)base=base.filter(r=>r.situacao===situacao);return base.map(r=>({...r,motivo:motivo(r)}))},[pacote,tipo,profissional,situacao])
 const ordenadas=useMemo(()=>{const prioridade=(r:Row)=>({falta_cnpj:1,cnpj_invalido:2,sem_nota:3,nota_sem_vinculo:4,nota_outra_empresa:5,possivel_duplicidade:6,vinculo_sugerido:7,aguardando_confirmacao:8,divergencia_valor:9,conferido_com_divergencia:10,conferido:20,corrigido_manual:21}[String(r.situacao)]||15);return[...filtradas].sort((a,b)=>ordem==='nome'?String(a.nome||'').localeCompare(String(b.nome||''),'pt-BR'):ordem==='competencia'?String(a.mes_ref||'').localeCompare(String(b.mes_ref||'')):ordem==='valor'?Number(b.valor_comissao||b.nf_valor||0)-Number(a.valor_comissao||a.nf_valor||0):prioridade(a)-prioridade(b)||String(a.nome||'').localeCompare(String(b.nome||''),'pt-BR'))},[filtradas,ordem])
 const esperado=ordenadas.reduce((s,r)=>s+Number(r.valor_comissao||0),0),notas=ordenadas.reduce((s,r)=>s+Number(r.nf_valor||0),0)
 const cols:Coluna[]=[{header:'Profissional / emitente',get:r=>r.nome||''},{header:'Unidade',get:r=>r.empresaNome||''},{header:'Competência',get:r=>fmtMes(r.mes_ref||'')},{header:'Motivo / resultado',get:r=>r.motivo||''},{header:'Valor esperado',get:r=>r.valor_comissao!=null?formatarMoeda(Number(r.valor_comissao)):''},{header:'Nota',get:r=>r.nf_numero||''},{header:'Valor da nota',get:r=>r.nf_valor!=null?formatarMoeda(Number(r.nf_valor)):''},{header:'Classificação',get:r=>SITUACAO_LABEL[r.situacao as Situacao]||r.situacao||''}]
 async function exportarIndividual(nome:string){const rows=pacote.linhas.filter(r=>r.nome===nome&&!conferido(r.situacao)).map(r=>({...r,motivo:motivo(r)}));if(!rows.length)return;await exportarPDF(`Pendências — ${nome} — ${fmtMes(inicio)} a ${fmtMes(fim)}`,cols,rows,`pendencias_${nome.replace(/\\W+/g,'_')}_${inicio}_${fim}`)}
 async function exportar(formato:'pdf'|'xlsx'){if(!ordenadas.length)return;const titulo=TIPOS.find(t=>t.v===tipo)?.l||'Relatório';if(formato==='pdf')await exportarPDF(`${titulo} — ${fmtMes(inicio)} a ${fmtMes(fim)}`,cols,ordenadas,`salao_${tipo}_${inicio}_${fim}`);else await exportarExcel(titulo,cols,ordenadas,`salao_${tipo}_${inicio}_${fim}`)}
 if(!SALAO_ENABLED)return null
 return <LayoutAdmin title="Salão — Relatórios"><div className="space-y-3">
  {erro&&<div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{erro}</div>}
  <section className="rounded-xl border bg-white p-3 shadow-sm"><div className="flex flex-wrap items-end gap-3"><div className="mr-auto"><h1 className="text-base font-semibold text-slate-900">Visão gerencial de pendências</h1><p className="text-xs text-slate-500">Identifique rapidamente quem exige ação e exporte somente o recorte atual.</p></div><div><label className="label-field">De</label><input type="month" className="input-field" value={inicio} onChange={e=>setInicio(e.target.value)}/></div><div><label className="label-field">Até</label><input type="month" className="input-field" min={inicio} value={fim} onChange={e=>setFim(e.target.value<inicio?inicio:e.target.value)}/></div><div className="min-w-44"><label className="label-field">Unidade</label><select className="input-field" value={empresaId} onChange={e=>setEmpresaId(e.target.value)}><option value="">Todas</option>{empresas.map(e=><option key={e.id} value={e.id}>{e.apelido||e.razao_social}</option>)}</select></div><button className="btn-secondary text-sm" disabled={loading} onClick={()=>carregar(true)}>{loading?'Atualizando…':'Atualizar'}</button></div></section>
  <section className="grid grid-cols-2 gap-2 md:grid-cols-4"><Kpi label="Pendências" valor={indicadores.pendencias} ativo={tipo==='pendencias'} onClick={()=>setTipo('pendencias')} tom="amber"/><Kpi label="Conferidos" valor={pacote.linhas.filter(r=>conferido(r.situacao)).length} ativo={tipo==='conferidos'} onClick={()=>setTipo('conferidos')} tom="blue"/><Kpi label="Sem vínculo" valor={indicadores.semNota+indicadores.semProfissional} ativo={tipo==='sem_vinculo'} onClick={()=>setTipo('sem_vinculo')} tom="red"/><Kpi label="Conferidos divergentes" valor={indicadores.divergencias} ativo={false} onClick={()=>setTipo('conferidos')} tom="violet"/></section>
  <section className="rounded-xl border bg-white p-3 shadow-sm"><div className="flex gap-2 overflow-x-auto pb-2">{TIPOS.map(t=><button key={t.v} onClick={()=>setTipo(t.v)} className={`min-w-fit rounded-lg border px-3 py-2 text-left transition ${tipo===t.v?'border-slate-900 bg-slate-900 text-white':'border-slate-200 hover:bg-slate-50'}`}><span className="block text-xs font-semibold">{t.l}</span><span className={`text-[10px] ${tipo===t.v?'text-slate-300':'text-slate-400'}`}>{t.d}</span></button>)}</div><div className="grid gap-3 border-t pt-3 md:grid-cols-[1fr_240px_auto]"><div><label className="label-field">Profissional</label><select className="input-field" value={profissional} onChange={e=>setProfissional(e.target.value)}><option value="">Todos os profissionais</option>{profissionais.map(n=><option key={n}>{n}</option>)}</select></div><div><label className="label-field">Situação específica</label><select className="input-field" value={situacao} onChange={e=>setSituacao(e.target.value)}><option value="">Todas</option>{Object.entries(SITUACAO_LABEL).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div><div className="flex items-end gap-2"><button onClick={()=>exportar('xlsx')} className="btn-secondary text-sm">Excel</button><button onClick={()=>exportar('pdf')} className="btn-primary text-sm">PDF</button></div></div></section>
  <section className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b p-3"><div><h2 className="font-semibold">{TIPOS.find(t=>t.v===tipo)?.l}</h2><p className="text-xs text-gray-500">{fmtMes(inicio)} a {fmtMes(fim)} · {ordenadas.length} registro(s) · esperado {formatarMoeda(esperado)} · notas {formatarMoeda(notas)}</p></div><select aria-label="Ordenar relatório" className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-medium text-slate-700" value={ordem} onChange={e=>setOrdem(e.target.value as typeof ordem)}><option value="prioridade">Prioridade</option><option value="nome">Profissional A–Z</option><option value="competencia">Competência</option><option value="valor">Maior valor</option></select></div>{loading&&pacote.linhas.length===0?<div className="py-14 text-center text-sm text-gray-400">Montando visão gerencial…</div>:ordenadas.length===0?<div className="py-14 text-center"><p className="text-sm font-medium text-slate-600">Nenhuma pendência neste recorte.</p><p className="mt-1 text-xs text-slate-400">Troque a visão, o profissional ou o período.</p></div>:<div className="overflow-x-auto"><table className="w-full"><thead><tr className="bg-gray-50">{cols.map(x=><th key={x.header} className="table-header">{x.header}</th>)}{tipo==='pendencias'&&<th className="table-header text-right">Enviar</th>}</tr></thead><tbody className="divide-y">{ordenadas.map((row,i)=><tr key={String(row.id||i)} className="hover:bg-slate-50">{cols.map(x=><td key={x.header} className="table-cell">{String(x.get(row)??'')}</td>)}{tipo==='pendencias'&&<td className="table-cell text-right"><button className="whitespace-nowrap rounded-lg bg-blue-50 px-3 py-2 text-xs font-semibold text-blue-700" onClick={()=>exportarIndividual(String(row.nome||''))}>PDF individual</button></td>}</tr>)}</tbody></table></div>}</section>
 </div></LayoutAdmin>
}
function Kpi({label,valor,ativo,onClick,tom='slate'}:{label:string;valor:number;ativo:boolean;onClick:()=>void;tom?:'slate'|'amber'|'red'|'blue'|'violet'}){const cor={slate:'text-slate-900',amber:'text-amber-700',red:'text-red-700',blue:'text-blue-700',violet:'text-violet-700'}[tom];return <button onClick={onClick} className={`rounded-xl border bg-white p-3 text-left shadow-sm transition hover:-translate-y-0.5 ${ativo?'ring-2 ring-slate-900':''}`}><span className="text-xs text-slate-500">{label}</span><b className={`block text-2xl ${cor}`}>{valor}</b></button>}
