'use client'
import { useCallback,useEffect,useState } from 'react'
import { useRouter } from 'next/navigation'
import LayoutAdmin from '../../../components/LayoutAdmin'
import { supabase,type Empresa } from '../../../lib/supabase'
import { SALAO_ENABLED } from '../../../lib/salao/config'
import { listarNotas,type NotaRecebida } from '../../../lib/salao/notas'
import { classificarNota } from '../../../lib/salao/conferencia'
import { formatarMoeda } from '../../../utils/calculoVT'
function mesAtual(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}function fimMes(m:string){const[y,mm]=m.split('-').map(Number);return new Date(y,mm,0).toISOString().slice(0,10)}
export default function OutrosServicosPage(){const router=useRouter();const[empresas,setEmpresas]=useState<Empresa[]>([]);const[empresaId,setEmpresaId]=useState('');const[inicio,setInicio]=useState(mesAtual());const[fim,setFim]=useState(mesAtual());const[busca,setBusca]=useState('');const[linhas,setLinhas]=useState<NotaRecebida[]>([]);const[msg,setMsg]=useState('');const[usuario,setUsuario]=useState<string|undefined>()
useEffect(()=>{if(!SALAO_ENABLED){router.replace('/dashboard');return}supabase.from('empresas').select('*').order('razao_social').then(({data})=>setEmpresas(data||[]));supabase.auth.getUser().then(({data})=>setUsuario(data.user?.email))},[router])
const carregar=useCallback(async()=>setLinhas(await listarNotas({empresaId:empresaId||undefined,de:`${inicio}-01`,ate:fimMes(fim),busca,classificacao:'outro_servico'})),[empresaId,inicio,fim,busca]);useEffect(()=>{if(SALAO_ENABLED)carregar()},[carregar])
async function devolver(n:NotaRecebida){const r=await classificarNota(n.id,'profissional',{usuario});if(!r.ok){setMsg(r.erro||'Erro.');return}setMsg('Nota devolvida à conferência.');carregar()}
if(!SALAO_ENABLED)return null;return <LayoutAdmin title="Salão — Notas de outros serviços"><div className="space-y-4"><section className="rounded-xl bg-slate-900 p-4 text-white"><div className="flex flex-wrap items-end gap-3"><div className="mr-auto"><h1 className="text-lg font-semibold">Notas de outros serviços</h1><p className="text-xs text-slate-300">Notas retiradas da conferência de profissionais.</p></div><div><label className="block text-xs text-slate-300">Mês inicial</label><input type="month" className="mt-1 rounded-lg border border-slate-600 bg-slate-800 px-3 py-2 text-sm" value={inicio} onChange={e=>setInicio(e.target.value)}/></div><div><label className="block text-xs text-slate-300">Mês final</label><input type="month" className="mt-1 rounded-lg border border-slate-600 bg-slate-800 px-3 py-2 text-sm" value={fim} min={inicio} onChange={e=>setFim(e.target.value<inicio?inicio:e.target.value)}/></div><div><label className="block text-xs text-slate-300">Empresa</label><select className="mt-1 rounded-lg border border-slate-600 bg-slate-800 px-3 py-2 text-sm" value={empresaId} onChange={e=>setEmpresaId(e.target.value)}><option value="">Todas</option>{empresas.map(e=><option key={e.id} value={e.id}>{e.apelido||e.razao_social}</option>)}</select></div></div></section>{msg&&<div className="rounded-lg border border-blue-200 bg-blue-50 p-3 text-sm text-blue-800">{msg}</div>}<section className="rounded-xl border bg-white shadow-sm"><div className="flex items-center gap-3 border-b p-3"><input className="input-field flex-1" placeholder="Buscar nota classificada" value={busca} onChange={e=>setBusca(e.target.value)}/><span className="text-xs text-gray-500">{linhas.length} nota(s) · {formatarMoeda(linhas.reduce((s,n)=>s+(n.valor||0),0))}</span></div><div className="overflow-x-auto"><table className="w-full"><thead><tr className="bg-gray-50"><th className="table-header">Emitente</th><th className="table-header">Nota</th><th className="table-header">Empresa</th><th className="table-header">Categoria</th><th className="table-header">Observação</th><th className="table-header text-right">Valor</th><th className="table-header text-right">Ação</th></tr></thead><tbody className="divide-y">{linhas.map(n=><tr key={n.id}><td className="table-cell font-medium">{n.emitente_nome||'—'}</td><td className="table-cell">{n.numero||'—'}</td><td className="table-cell">{n.empresaNome}</td><td className="table-cell">{n.categoria_outro_servico||'Outro serviço'}</td><td className="table-cell">{n.observacao||'—'}</td><td className="table-cell text-right">{formatarMoeda(n.valor||0)}</td><td className="table-cell text-right"><button onClick={()=>devolver(n)} className="text-xs font-medium text-blue-700">Devolver à conferência</button></td></tr>)}</tbody></table></div></section></div></LayoutAdmin>}
