'use client'

import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { useRouter } from 'next/navigation'
import LayoutAdmin from '../../../components/LayoutAdmin'
import { supabase, type Empresa } from '../../../lib/supabase'
import { SALAO_ENABLED } from '../../../lib/salao/config'
import { sincronizarNFSe } from '../../../lib/salao/certificados'
import { listarNotas, resumoNotas, type NotaRecebida } from '../../../lib/salao/notas'
import { classificarNota, editarNota, excluirNota, setNotaConferida } from '../../../lib/salao/conferencia'
import { formatarMoeda, MESES } from '../../../utils/calculoVT'

function mesAtual(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function fimMes(m:string){const[y,mm]=m.split('-').map(Number);return new Date(y,mm,0).toISOString().slice(0,10)}
function mesesEntre(a:string,b:string){const out:string[]=[];let[y,m]=a.split('-').map(Number);const[fy,fm]=b.split('-').map(Number);while(y*12+m<=fy*12+fm&&out.length<120){out.push(`${y}-${String(m).padStart(2,'0')}`);m++;if(m>12){m=1;y++}}return out}
function fmtData(v:string|null){if(!v)return '—';const[a,m,d]=v.split('-');return `${d}/${m}/${a}`}
function fmtDoc(v:string|null){const s=(v||'').replace(/\D/g,'');return s||'—'}
type Filtro='todas'|'pendentes'|'conferidas'|'divergentes'|'analise'

export default function NotasPage(){
 const router=useRouter();const[empresas,setEmpresas]=useState<Empresa[]>([]);const[empresaId,setEmpresaId]=useState('');const[inicio,setInicio]=useState(mesAtual());const[fim,setFim]=useState(mesAtual());const[compInicio,setCompInicio]=useState('');const[compFim,setCompFim]=useState('');const[busca,setBusca]=useState('');const[buscaAplicada,setBuscaAplicada]=useState('');const[filtro,setFiltro]=useState<Filtro>('pendentes');const[linhas,setLinhas]=useState<NotaRecebida[]>([]);const[loading,setLoading]=useState(false);const[baixando,setBaixando]=useState(false);const[importando,setImportando]=useState(false);const[reconferindo,setReconferindo]=useState(false);const[msg,setMsg]=useState('');const[selecionada,setSelecionada]=useState<NotaRecebida|null>(null);const[editando,setEditando]=useState(false);const[form,setForm]=useState<Record<string,string>>({});const[usuario,setUsuario]=useState<string|undefined>();const requisicao=useRef(0);const seletorXml=useRef<HTMLInputElement>(null);const[acaoId,setAcaoId]=useState('')
 useEffect(()=>{if(!SALAO_ENABLED){router.replace('/dashboard');return}supabase.from('empresas').select('*').order('razao_social').then(({data})=>setEmpresas(data||[]));supabase.auth.getUser().then(({data})=>setUsuario(data.user?.email))},[router])
 const carregar=useCallback(async()=>{const id=++requisicao.current;setLoading(true);try{const r=await listarNotas({empresaId:empresaId||undefined,de:inicio?`${inicio}-01`:undefined,ate:fim?fimMes(fim):undefined,busca:buscaAplicada,classificacao:'profissional'});if(id===requisicao.current)setLinhas(r)}catch(e){if(id===requisicao.current)setMsg(e instanceof Error?e.message:'Erro ao carregar notas.')}finally{if(id===requisicao.current)setLoading(false)}},[empresaId,inicio,fim,buscaAplicada])
 useEffect(()=>{const t=setTimeout(()=>setBuscaAplicada(busca.trim()),300);return()=>clearTimeout(t)},[busca])
 useEffect(()=>{if(SALAO_ENABLED)carregar()},[carregar])
 const visiveis=useMemo(()=>linhas.filter(n=>{const comp=n.competenciaEfetiva||'';if(compInicio&&comp<compInicio)return false;if(compFim&&comp>compFim)return false;if(filtro==='pendentes')return !n.conferida&&!n.analise_manual;if(filtro==='conferidas')return n.conferida;if(filtro==='divergentes')return !!n.competenciaEfetiva&&!!n.data_emissao&&n.competenciaEfetiva!==n.data_emissao.slice(0,7);if(filtro==='analise')return !!n.analise_manual;return true}),[linhas,filtro,compInicio,compFim])
 const resumo=resumoNotas(linhas)
 async function baixar(){setBaixando(true);setMsg('Baixando notas do gov.br...');const r=await sincronizarNFSe(empresaId||undefined,false);setBaixando(false);if(r.erro){setMsg(r.erro);return}setMsg('Download concluído. A lista foi atualizada.');carregar()}
 async function importarArquivos(files:FileList|null){if(!files?.length)return;if(!empresaId){setMsg('Selecione uma empresa antes de importar os XMLs.');return}setImportando(true);setMsg('Lendo e validando os XMLs…');const formData=new FormData();formData.set('empresa_id',empresaId);Array.from(files).forEach(a=>formData.append('arquivos',a));try{const res=await fetch('/api/nfse/importar-xml',{method:'POST',body:formData});const j=await res.json().catch(()=>null);if(!res.ok){setMsg(j?.erro||`Falha HTTP ${res.status} ao importar.`);return}const auto=j.conferencia?` Conferência automática: ${j.conferencia.conferidas} vínculo(s), ${j.conferencia.divergencias} divergência(s).`:'';const resumo=`${j.importadas} importada(s), ${j.duplicadas} duplicada(s) e ${j.rejeitadas} rejeitada(s), em ${j.arquivos} XML(s).${auto}`;setMsg(j.erros?.length?`${resumo} ${j.erros.join(' | ')}`:resumo);await carregar()}catch(e){setMsg(e instanceof Error?e.message:'Falha ao importar XMLs.')}finally{setImportando(false)}}
 async function reprocessarConferencia(){const de=compInicio||inicio,ate=compFim||fim;if(!de||!ate||de>ate){setMsg('Informe um período válido para a reconferência.');return}setReconferindo(true);setMsg('Reprocessando a conferência do período…');let conferidas=0,pendentes=0,divergencias=0;try{for(const competencia of mesesEntre(de,ate)){const res=await fetch('/api/salao/conferencia',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({acao:'reconciliar',competencia,empresaId:empresaId||undefined})});const j=await res.json().catch(()=>null);if(!res.ok||!j?.ok)throw new Error(j?.erro||`Falha ao conferir ${competencia}.`);conferidas+=Number(j.conferidas||0);pendentes+=Number(j.pendentes||0);divergencias+=Number(j.divergencias||0)}setMsg(`Reconferência concluída: ${conferidas} novo(s) vínculo(s), ${pendentes} pendente(s) e ${divergencias} divergência(s).`);await carregar()}catch(e){setMsg(e instanceof Error?e.message:'Falha ao reprocessar conferência.')}finally{setReconferindo(false)}}
 function abrirEdicao(n:NotaRecebida){setSelecionada(n);setEditando(true);setForm({emitente_nome:n.emitente_nome||'',documento:n.documento||'',numero:n.numero||'',data_emissao:n.data_emissao||'',competencia:n.competenciaEfetiva||'',valor:String(n.valor||''),observacao:n.observacao||''})}
 async function salvar(){if(!selecionada)return;const r=await editarNota(selecionada.id,form,usuario);if(!r.ok){setMsg(r.erro||'Erro ao salvar.');return}setMsg('Nota atualizada e vínculos reavaliados.');setEditando(false);setSelecionada(null);carregar()}
 async function outro(n:NotaRecebida){if(acaoId)return;setAcaoId(n.id);setLinhas(v=>v.filter(x=>x.id!==n.id));const r=await classificarNota(n.id,'outro_servico',{categoria:'Outro serviço',observacao:'Classificação rápida pelo painel',usuario});if(!r.ok){setMsg(r.erro||'Erro ao classificar.');carregar();setAcaoId('');return}setMsg('Nota movida para Outros serviços em um clique.');setAcaoId('')}
 async function conferir(n:NotaRecebida){if(acaoId)return;setAcaoId(n.id);const proximo=!n.conferida;setLinhas(v=>v.map(x=>x.id===n.id?{...x,conferida:proximo}:x));const r=await setNotaConferida(n.id,proximo,usuario);if(!r.ok){setMsg(r.erro||'Erro ao atualizar conferência.');carregar();setAcaoId('');return}setMsg(proximo?'Nota marcada como conferida.':'Nota voltou para pendentes.');setAcaoId('')}
 async function excluir(n:NotaRecebida){if(acaoId)return;setAcaoId(n.id);setLinhas(v=>v.filter(x=>x.id!==n.id));const r=await excluirNota(n.id,'Exclusão rápida pelo painel',usuario);if(!r.ok){setMsg(r.erro||'Erro ao excluir.');carregar();setAcaoId('');return}setMsg('Nota removida. Você pode restaurá-la na auditoria.');setAcaoId('')}
 if(!SALAO_ENABLED)return null
 return <LayoutAdmin title="Salão — Notas baixadas"><div className="space-y-4">
  {msg&&<div className="rounded-lg border border-blue-200 bg-blue-50 px-4 py-3 text-sm text-blue-800">{msg}</div>}
  <section className="rounded-xl bg-slate-900 p-4 text-white"><div className="flex flex-wrap items-end gap-3"><div className="mr-auto"><h1 className="text-lg font-semibold">Notas baixadas</h1><p className="text-xs text-slate-300">Consulte, classifique e corrija as NFS-e recebidas.</p></div><div><label className="block text-xs text-slate-300">Emissão inicial</label><input type="month" className="mt-1 rounded-lg border border-slate-600 bg-slate-800 px-3 py-2 text-sm" value={inicio} onChange={e=>setInicio(e.target.value)}/></div><div><label className="block text-xs text-slate-300">Emissão final</label><input type="month" className="mt-1 rounded-lg border border-slate-600 bg-slate-800 px-3 py-2 text-sm" value={fim} min={inicio} onChange={e=>setFim(e.target.value<inicio?inicio:e.target.value)}/></div><div><label className="block text-xs text-slate-300">Competência inicial</label><input type="month" className="mt-1 rounded-lg border border-slate-600 bg-slate-800 px-3 py-2 text-sm" value={compInicio} onChange={e=>setCompInicio(e.target.value)}/></div><div><label className="block text-xs text-slate-300">Competência final</label><input type="month" className="mt-1 rounded-lg border border-slate-600 bg-slate-800 px-3 py-2 text-sm" value={compFim} min={compInicio||undefined} onChange={e=>setCompFim(e.target.value)}/></div><div className="min-w-48"><label className="block text-xs text-slate-300">Empresa</label><select className="mt-1 w-full rounded-lg border border-slate-600 bg-slate-800 px-3 py-2 text-sm" value={empresaId} onChange={e=>setEmpresaId(e.target.value)}><option value="">Todas</option>{empresas.map(e=><option key={e.id} value={e.id}>{e.apelido||e.razao_social}</option>)}</select></div><button onClick={()=>{setInicio(mesAtual());setFim(mesAtual());setCompInicio('');setCompFim('');setEmpresaId('');setBusca('');setFiltro('pendentes')}} className="rounded-lg border border-slate-600 px-3 py-2 text-sm text-slate-200 hover:bg-slate-800">Limpar filtros</button><input ref={seletorXml} type="file" accept=".zip,.xml,application/zip,text/xml,application/xml" multiple className="hidden" onChange={e=>{importarArquivos(e.target.files);e.target.value=''}}/><button onClick={()=>{if(!empresaId){setMsg('Selecione uma empresa antes de importar.');return}seletorXml.current?.click()}} disabled={importando} className="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-medium hover:bg-emerald-500 disabled:opacity-50">{importando?'Importando XMLs…':'Importar ZIP/XML'}</button><button onClick={reprocessarConferencia} disabled={reconferindo} className="rounded-lg bg-violet-600 px-4 py-2 text-sm font-medium hover:bg-violet-500 disabled:opacity-50">{reconferindo?'Reconferindo…':'Reprocessar conferência'}</button><button onClick={baixar} disabled={baixando} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium hover:bg-blue-500 disabled:opacity-50">{baixando?'Baixando...':'Baixar do gov.br'}</button></div></section>
  <section className="grid grid-cols-2 gap-2 md:grid-cols-5">{([{k:'todas',v:resumo.total,l:'Todas'},{k:'pendentes',v:resumo.pendentes,l:'Pendentes'},{k:'conferidas',v:resumo.conferidas,l:'Conferidas'},{k:'divergentes',v:resumo.divergentes,l:'Divergentes'},{k:'analise',v:linhas.filter(n=>n.analise_manual).length,l:'Análise'}] as {k:Filtro;v:number;l:string}[]).map(x=><button key={x.k} onClick={()=>setFiltro(x.k)} className={`rounded-xl border bg-white p-3 text-left shadow-sm ${filtro===x.k?'ring-2 ring-blue-500':''}`}><b className="block text-xl text-gray-900">{x.v}</b><span className="text-xs text-gray-500">{x.l}</span></button>)}</section>
  <section className="rounded-xl border bg-white shadow-sm"><div className="flex flex-wrap items-center gap-2 border-b p-3"><input type="search" className="input-field flex-1" placeholder="Buscar emitente, CNPJ ou número" value={busca} onChange={e=>setBusca(e.target.value)}/><span className="text-xs text-gray-500">{visiveis.length} nota(s) · {formatarMoeda(visiveis.reduce((s,n)=>s+(n.valor||0),0))}</span></div>{loading?<div className="py-14 text-center text-sm text-gray-400">Carregando...</div>:visiveis.length===0?<div className="py-14 text-center"><p className="text-sm font-medium text-gray-600">Nenhuma nota encontrada.</p><p className="mt-1 text-xs text-gray-400">Limpe ou ajuste os filtros para ampliar a busca.</p></div>:<div className="overflow-x-auto"><table className="w-full"><thead><tr className="bg-gray-50"><th className="table-header">Emitente</th><th className="table-header">CPF/CNPJ</th><th className="table-header">Nota</th><th className="table-header">Emissão</th><th className="table-header">Competência</th><th className="table-header text-right">Valor</th><th className="table-header">Situação</th><th className="table-header text-right">Ações rápidas</th></tr></thead><tbody className="divide-y">{visiveis.map(n=><tr key={n.id} className="hover:bg-gray-50"><td className="table-cell font-medium">{n.emitente_nome||'—'}</td><td className="table-cell text-xs">{fmtDoc(n.documento)}</td><td className="table-cell">{n.numero||'—'}</td><td className="table-cell">{fmtData(n.data_emissao)}</td><td className="table-cell">{n.competenciaEfetiva?MESES[Number(n.competenciaEfetiva.slice(5,7))-1]+'/'+n.competenciaEfetiva.slice(0,4):'—'}</td><td className="table-cell text-right">{formatarMoeda(n.valor||0)}</td><td className="table-cell"><span className={`rounded-full px-2 py-1 text-xs ${n.conferida?'bg-green-100 text-green-700':'bg-amber-100 text-amber-700'}`}>{n.conferida?'Conferida':n.analise_manual?'Análise':'Pendente'}</span></td><td className="table-cell text-right whitespace-nowrap"><button onClick={()=>conferir(n)} className={`mr-2 rounded-md px-2 py-1 text-xs font-semibold ${n.conferida?'bg-green-100 text-green-700':'bg-slate-100 text-slate-700'}`}>{n.conferida?'✓ Conferida':'Conferir'}</button><button onClick={()=>abrirEdicao(n)} className="mr-2 text-xs text-blue-700">Editar</button><button onClick={()=>outro(n)} className="mr-2 text-xs text-amber-700">Outro serviço</button><button onClick={()=>excluir(n)} className="text-xs text-red-600">Excluir</button></td></tr>)}</tbody></table></div>}</section>
  {editando&&selecionada&&<section className="rounded-xl border border-blue-200 bg-white p-4 shadow-sm"><div className="mb-3 flex justify-between"><div><h2 className="font-semibold">Editar nota {selecionada.numero||''}</h2><p className="text-xs text-gray-500">A alteração será registrada no histórico e poderá desfazer vínculo incompatível.</p></div><button onClick={()=>setEditando(false)}>×</button></div><div className="grid gap-3 md:grid-cols-4"><div><label className="label-field">Emitente</label><input className="input-field" value={form.emitente_nome} onChange={e=>setForm({...form,emitente_nome:e.target.value})}/></div><div><label className="label-field">CPF/CNPJ</label><input className="input-field" value={form.documento} onChange={e=>setForm({...form,documento:e.target.value})}/></div><div><label className="label-field">Data</label><input type="date" className="input-field" value={form.data_emissao} onChange={e=>setForm({...form,data_emissao:e.target.value})}/></div><div><label className="label-field">Competência</label><input type="month" className="input-field" value={form.competencia} onChange={e=>setForm({...form,competencia:e.target.value})}/></div><div><label className="label-field">Número</label><input className="input-field" value={form.numero} onChange={e=>setForm({...form,numero:e.target.value})}/></div><div><label className="label-field">Valor</label><input className="input-field" value={form.valor} onChange={e=>setForm({...form,valor:e.target.value})}/></div><div className="md:col-span-2"><label className="label-field">Observação</label><input className="input-field" value={form.observacao} onChange={e=>setForm({...form,observacao:e.target.value})}/></div></div><div className="mt-4 flex justify-end gap-2"><button className="btn-secondary" onClick={()=>setEditando(false)}>Cancelar</button><button className="btn-primary" onClick={salvar}>Salvar alterações</button></div></section>}
 </div></LayoutAdmin>
}
