'use client'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import LayoutAdmin from '../../../components/LayoutAdmin'
import { supabase, type Empresa } from '../../../lib/supabase'
import { SALAO_ENABLED } from '../../../lib/salao/config'
import { formatarMoeda } from '../../../utils/calculoVT'

type Nota={id:string;emitente_nome:string|null;documento:string|null;numero:string|null;data_emissao:string|null;competencia:string|null;valor:number|null}
type Resultado={empresa?:string;encontradas:number;gravadas:number;existentes:number;paginas:number;mensagens?:string[]}
function hoje(){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function mesAtual(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function primeiroDia(m:string){return `${m}-01`}
function ultimoDia(m:string){const[y,mm]=m.split('-').map(Number);const d=new Date(y,mm,0);return `${y}-${String(mm).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function data(v:string|null){if(!v)return '—';const[a,m,d]=v.slice(0,10).split('-');return `${d}/${m}/${a}`}
function doc(v:string|null){const x=(v||'').replace(/\D/g,'');return x||'—'}

export default function IssDfPage(){
 const router=useRouter();const[empresas,setEmpresas]=useState<Empresa[]>([]);const[empresaId,setEmpresaId]=useState('');const[inscricaoMunicipal,setInscricaoMunicipal]=useState('');const[mes,setMes]=useState(mesAtual());const[notas,setNotas]=useState<Nota[]>([]);const[busca,setBusca]=useState('');const[ordem,setOrdem]=useState<'emissao'|'prestador'|'nota'|'valor'|'competencia'>('emissao');const[direcao,setDirecao]=useState<'asc'|'desc'>('desc');const[loading,setLoading]=useState(false);const[sync,setSync]=useState(false);const[msg,setMsg]=useState('');const[resultado,setResultado]=useState<Resultado|null>(null)
 useEffect(()=>{if(!SALAO_ENABLED){router.replace('/dashboard');return}supabase.from('empresas').select('*').order('razao_social').then(({data})=>setEmpresas(data||[]))},[router])
 const carregar=useCallback(async()=>{if(!empresaId){setNotas([]);return}setLoading(true);const q=new URLSearchParams({empresa_id:empresaId,inicio:primeiroDia(mes),fim:ultimoDia(mes)});const r=await fetch(`/api/nfse/issdf?${q}`,{cache:'no-store'});const j=await r.json().catch(()=>null);setLoading(false);if(!r.ok){setMsg(j?.erro||'Falha ao listar notas.');return}setNotas(j?.notas||[])},[empresaId,mes])
 useEffect(()=>{carregar()},[carregar])
 async function sincronizar(){if(!empresaId){setMsg('Selecione uma unidade.');return}if(!inscricaoMunicipal.trim()){setMsg('Informe a inscrição municipal da unidade no ISS-DF.');return}if(mes>mesAtual()){setMes(mesAtual());setMsg('A competência não pode ser posterior ao mês atual.');return}setSync(true);setMsg('Consultando somente notas recebidas no ISS-DF…');setResultado(null);const r=await fetch('/api/nfse/issdf',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({empresa_id:empresaId,inscricao_municipal:inscricaoMunicipal,inicio:primeiroDia(mes),fim:ultimoDia(mes)})});const j=await r.json().catch(()=>null);setSync(false);if(!r.ok){setMsg(j?.erro||`Falha HTTP ${r.status}.`);return}setResultado(j);setMsg(`Consulta concluída: ${j.gravadas} nota(s) nova(s) recebida(s) incluída(s).`);carregar()}
 const visiveis=useMemo(()=>{const q=busca.trim().toLowerCase();const base=(!q?notas:notas.filter(n=>`${n.emitente_nome} ${n.documento} ${n.numero} ${n.data_emissao} ${n.competencia} ${n.valor}`.toLowerCase().includes(q)));const valorDe=(n:Nota)=>ordem==='prestador'?String(n.emitente_nome||''):ordem==='nota'?String(n.numero||''):ordem==='valor'?Number(n.valor||0):ordem==='competencia'?String(n.competencia||''):String(n.data_emissao||'');return[...base].sort((a,b)=>{const av=valorDe(a),bv=valorDe(b);const r=typeof av==='number'&&typeof bv==='number'?av-bv:String(av).localeCompare(String(bv),'pt-BR',{numeric:true});return direcao==='asc'?r:-r})},[notas,busca,ordem,direcao])
 if(!SALAO_ENABLED)return null
 return <LayoutAdmin title="Salão — Notas recebidas ISS-DF"><div className="space-y-4">
  {msg&&<div className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-sm text-blue-800">{msg}</div>}
  <section className="overflow-hidden rounded-2xl bg-gradient-to-br from-slate-950 to-blue-950 p-5 text-white shadow-lg">
   <div className="flex flex-wrap items-end gap-3"><div className="mr-auto max-w-xl"><span className="rounded-full bg-blue-500/20 px-3 py-1 text-xs text-blue-200">Base histórica ABRASF 2.04</span><h1 className="mt-3 text-xl font-bold">Notas recebidas no ISS-DF</h1><p className="mt-1 text-sm text-slate-300">Busca exclusivamente serviços tomados pela unidade no mês selecionado. Nenhuma nota emitida pela empresa é importada.</p></div>
   <div className="min-w-56"><label className="block text-xs text-slate-300">Unidade / tomador</label><select className="mt-1 w-full rounded-lg border border-slate-600 bg-slate-800 px-3 py-2 text-sm" value={empresaId} onChange={e=>setEmpresaId(e.target.value)}><option value="">Selecione</option>{empresas.map(e=><option key={e.id} value={e.id}>{e.apelido||e.razao_social}</option>)}</select></div><div><label className="block text-xs text-slate-300">Inscrição municipal</label><input className="mt-1 w-40 rounded-lg border border-slate-600 bg-slate-800 px-3 py-2 text-sm" inputMode="numeric" placeholder="CF/DF" value={inscricaoMunicipal} onChange={e=>setInscricaoMunicipal(e.target.value.replace(/\D/g,''))}/></div>
   <div><label className="block text-xs text-slate-300">Mês da consulta</label><input type="month" max={mesAtual()} className="mt-1 rounded-lg border border-slate-600 bg-slate-800 px-3 py-2 text-sm" value={mes} onChange={e=>setMes(e.target.value)}/></div><button onClick={sincronizar} disabled={sync||!empresaId} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-bold hover:bg-blue-500 disabled:opacity-50">{sync?'Consultando ISS-DF…':'Buscar notas recebidas'}</button></div>
  </section>
  {resultado&&<section className="grid grid-cols-2 gap-2 md:grid-cols-4"><Kpi l="Encontradas no ISS-DF" v={resultado.encontradas}/><Kpi l="Novas incluídas" v={resultado.gravadas} cor="emerald"/><Kpi l="Já existentes" v={resultado.existentes}/><Kpi l="Páginas consultadas" v={resultado.paginas}/></section>}
  {resultado?.mensagens&&resultado.mensagens.length>0&&<section className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs text-amber-800">{resultado.mensagens.map((m,i)=><div key={i}>{m}</div>)}</section>}
  <section className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="flex flex-wrap items-center gap-3 border-b p-3"><div className="mr-auto"><h2 className="font-semibold">Recebidas do ISS-DF</h2><p className="text-xs text-slate-500">{visiveis.length} nota(s) · {formatarMoeda(visiveis.reduce((s,n)=>s+Number(n.valor||0),0))}</p></div><input className="input-field min-w-64 flex-1" placeholder="Buscar prestador, CNPJ, nota, data, competência ou valor" value={busca} onChange={e=>setBusca(e.target.value)}/><select aria-label="Classificar por" className="input-field max-w-48" value={ordem} onChange={e=>setOrdem(e.target.value as typeof ordem)}><option value="emissao">Data de emissão</option><option value="competencia">Competência</option><option value="prestador">Prestador</option><option value="nota">Número da nota</option><option value="valor">Valor</option></select><select aria-label="Direção" className="input-field max-w-40" value={direcao} onChange={e=>setDirecao(e.target.value as typeof direcao)}><option value="asc">Crescente</option><option value="desc">Decrescente</option></select></div>
   {loading?<div className="py-14 text-center text-sm text-slate-400">Carregando…</div>:!empresaId?<Vazio t="Selecione uma unidade para consultar."/>:visiveis.length===0?<Vazio t="Nenhuma nota do ISS-DF neste período."/>:<div className="overflow-x-auto"><table className="w-full"><thead><tr className="bg-slate-50"><th className="table-header">Prestador</th><th className="table-header">CPF/CNPJ</th><th className="table-header">Nota</th><th className="table-header">Emissão</th><th className="table-header">Competência</th><th className="table-header text-right">Valor</th></tr></thead><tbody className="divide-y">{visiveis.map(n=><tr key={n.id} className="hover:bg-slate-50"><td className="table-cell font-medium">{n.emitente_nome||'Prestador não identificado'}</td><td className="table-cell text-xs">{doc(n.documento)}</td><td className="table-cell">{n.numero||'—'}</td><td className="table-cell">{data(n.data_emissao)}</td><td className="table-cell">{n.competencia||'—'}</td><td className="table-cell text-right">{formatarMoeda(Number(n.valor||0))}</td></tr>)}</tbody></table></div>}
  </section>
 </div></LayoutAdmin>
}
function Kpi({l,v,cor='slate'}:{l:string;v:number;cor?:'slate'|'emerald'}){return <div className="rounded-xl border bg-white p-3 shadow-sm"><span className="text-xs text-slate-500">{l}</span><b className={`block text-2xl ${cor==='emerald'?'text-emerald-700':'text-slate-900'}`}>{v}</b></div>}
function Vazio({t}:{t:string}){return <div className="py-14 text-center text-sm text-slate-400">{t}</div>}
