'use client'
import { useCallback,useEffect,useMemo,useRef,useState } from 'react'
import { useRouter } from 'next/navigation'
import LayoutAdmin from '../../../components/LayoutAdmin'
import { supabase,type Empresa } from '../../../lib/supabase'
import { SALAO_ENABLED } from '../../../lib/salao/config'
import { consultarConferencia,vincularNota,vincularMultiplas,type LinhaConsulta } from '../../../lib/salao/conferencia'
import { formatarMoeda,MESES } from '../../../utils/calculoVT'

type Sugestao={id:string;profissional:LinhaConsulta;notas:LinhaConsulta[];selecionada:boolean}
function norm(s:string|null|undefined){return(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\d/g,' ').replace(/\b(ltda|me|mei|eireli|sa)\b/g,' ').replace(/[^a-z]+/g,' ').trim().replace(/\s+/g,' ')}
function mesesEntre(a:string,b:string){if(!a||!b)return[];const out:string[]=[];let[y,m]=a.split('-').map(Number);const[fy,fm]=b.split('-').map(Number);while(y*12+m<=fy*12+fm&&out.length<24){out.push(`${y}-${String(m).padStart(2,'0')}`);m++;if(m>12){m=1;y++}}return out}
function fmtMes(m:string){const[a,mm]=m.split('-').map(Number);return mm?`${MESES[mm-1]}/${a}`:m}
function fmtData(v:string|null){if(!v)return'—';const[a,m,d]=v.slice(0,10).split('-');return d?`${d}/${m}/${a}`:v}
async function buscarMes(competencia:string,empresaId:string){const f={competencia,empresaId:empresaId||undefined};const p=await consultarConferencia(f,{campo:'nome',dir:'asc'},1,500);const n=Math.ceil(p.total/500);if(n<=1)return p.linhas;const ds=await Promise.all(Array.from({length:n-1},(_,i)=>consultarConferencia(f,{campo:'nome',dir:'asc'},i+2,500)));return[...p.linhas,...ds.flatMap(x=>x.linhas)]}
function combinacaoUnica(notas:LinhaConsulta[],alvo:number){const alvoCent=Math.round(alvo*100);const dp=new Map<number,LinhaConsulta[][]>([[0,[[]]]]);for(const nota of notas.slice(0,24)){const valor=Math.round(Number(nota.nf_valor||0)*100);if(valor<=0||valor>alvoCent)continue;const atual=[...dp.entries()];for(const[soma,combos]of atual){const nova=soma+valor;if(nova>alvoCent)continue;const destino=dp.get(nova)||[];for(const combo of combos){if(combo.length>=6)continue;const ids=combo.map(x=>x.id).concat(nota.id).sort().join('|');if(!destino.some(x=>x.map(y=>y.id).sort().join('|')===ids))destino.push([...combo,nota]);if(destino.length>=2)break}dp.set(nova,destino.slice(0,2))}if((dp.get(alvoCent)?.length||0)>1)return null}const achadas=dp.get(alvoCent)||[];return achadas.length===1?achadas[0]:null}
function montar(linhas:LinhaConsulta[]):Sugestao[]{const pros=linhas.filter(r=>r.tipo==='comissao'&&!r.nota_id&&!r.analise_manual);const notas=linhas.filter(r=>r.tipo==='nota'&&r.situacao==='nota_sem_vinculo'&&!r.analise_manual);const grupos=new Map<string,LinhaConsulta[]>();const chave=(r:LinhaConsulta)=>`${r.empresa_id}|${norm(r.nome)}`;for(const n of notas){const k=chave(n);if(!norm(n.nome)||!(Number(n.nf_valor)>0))continue;(grupos.get(k)||grupos.set(k,[]).get(k)!).push(n)}const candidatas:Sugestao[]=[];for(const p of pros){const alvo=Number(p.valor_comissao||0);if(!norm(p.nome)||!(alvo>0))continue;const combo=combinacaoUnica(grupos.get(chave(p))||[],alvo);if(!combo?.length)continue;candidatas.push({id:`${p.id}|${combo.map(n=>n.id).sort().join('+')}`,profissional:p,notas:combo,selecionada:true})}const uso=new Map<string,number>();for(const s of candidatas)for(const n of s.notas)uso.set(n.id,(uso.get(n.id)||0)+1);return candidatas.filter(s=>s.notas.every(n=>uso.get(n.id)===1)).sort((a,b)=>String(a.profissional.nome||'').localeCompare(String(b.profissional.nome||''),'pt-BR'))}

export default function PreVinculacaoPage(){const router=useRouter();const[inicio,setInicio]=useState('');const[fim,setFim]=useState('');const[empresaId,setEmpresaId]=useState('');const[empresas,setEmpresas]=useState<Empresa[]>([]);const[sugestoes,setSugestoes]=useState<Sugestao[]>([]);const[loading,setLoading]=useState(false);const[acao,setAcao]=useState('');const[msg,setMsg]=useState('');const req=useRef(0);const cache=useRef(new Map<string,Sugestao[]>())
 useEffect(()=>{if(!SALAO_ENABLED){router.replace('/dashboard');return}supabase.from('empresas').select('*').order('razao_social').then(({data})=>setEmpresas(data||[]))},[router])
 const checar=useCallback(async()=>{const id=++req.current;if(!inicio||!fim){setSugestoes([]);return}const chaveCache=`${inicio}|${fim}|${empresaId}`;const salvo=cache.current.get(chaveCache);if(salvo){setSugestoes(salvo.map(s=>({...s,selecionada:true})));setMsg('Pré-visualização recuperada instantaneamente.');return}setLoading(true);setMsg('');try{const rs=await Promise.all(mesesEntre(inicio,fim).map(m=>buscarMes(m,empresaId)));const s=montar(rs.flat());cache.current.set(chaveCache,s);if(id===req.current){setSugestoes(s);setMsg(s.length?`${s.length} correspondência(s) segura(s), incluindo somas de várias notas.`:'Nenhuma combinação única de nome e valor foi encontrada.')}}catch(e){if(id===req.current)setMsg(e instanceof Error?e.message:'Erro ao executar a checagem.')}finally{if(id===req.current)setLoading(false)}},[inicio,fim,empresaId])
 async function gravar(s:Sugestao){return s.notas.length===1?vincularNota(s.profissional.id,{id:s.notas[0].id,numero:s.notas[0].nf_numero,valor:s.notas[0].nf_valor,data_emissao:s.notas[0].nf_data}):vincularMultiplas(s.profissional.id,s.notas.map(n=>n.id))}
 async function confirmar(s:Sugestao){if(acao)return;setAcao(s.id);const r=await gravar(s);setAcao('');if(!r.ok){setMsg(r.erro||'Não foi possível confirmar o vínculo.');return}cache.current.clear();setSugestoes(v=>v.filter(x=>x.id!==s.id));setMsg(`${s.notas.length} nota(s) vinculada(s) e marcadas como conferidas.`)}
 async function confirmarSelecionadas(){const alvo=sugestoes.filter(s=>s.selecionada);if(!alvo.length||acao)return;setAcao('lote');let ok=0;for(const s of alvo){const r=await gravar(s);if(r.ok)ok++;else{setMsg(`${ok} vínculo(s) confirmado(s). A operação parou em ${s.profissional.nome}: ${r.erro||'erro'}`);setSugestoes(v=>v.filter(x=>!alvo.slice(0,ok).some(y=>y.id===x.id)));setAcao('');return}}setSugestoes(v=>v.filter(x=>!alvo.some(y=>y.id===x.id)));setAcao('');setMsg(`${ok} vínculo(s) confirmado(s) e conferido(s).`)}
 function limpar(){req.current++;setInicio('');setFim('');setEmpresaId('');setSugestoes([]);setMsg('');setLoading(false);cache.current.clear()}
 const selecionadas=sugestoes.filter(s=>s.selecionada).length
 if(!SALAO_ENABLED)return null
 return <LayoutAdmin title="Salão — Pré-vinculação"><div className="space-y-3">
  <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="bg-gradient-to-r from-blue-950 via-blue-900 to-indigo-900 p-5 text-white"><span className="rounded-full bg-white/10 px-2 py-1 text-[10px] font-bold uppercase tracking-wider text-blue-100">Conferência assistida</span><h1 className="mt-3 text-xl font-semibold">Pré-vinculação inteligente</h1><p className="mt-1 max-w-3xl text-sm text-blue-100">O sistema cruza nome e valor exatos no período. Nada é gravado antes da sua confirmação.</p></div><div className="grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-[170px_170px_1fr_auto]"><div><label className="label-field">Mês inicial</label><input type="month" className="input-field" value={inicio} onChange={e=>{setInicio(e.target.value);if(fim&&e.target.value>fim)setFim(e.target.value)}}/></div><div><label className="label-field">Mês final</label><input type="month" min={inicio} className="input-field" value={fim} onChange={e=>setFim(e.target.value)}/></div><div><label className="label-field">Unidade</label><select className="input-field" value={empresaId} onChange={e=>setEmpresaId(e.target.value)}><option value="">Todas as unidades</option>{empresas.map(e=><option key={e.id} value={e.id}>{e.apelido||e.razao_social}</option>)}</select></div><div className="flex items-end gap-2"><button className="btn-secondary" onClick={limpar}>Limpar</button><button className="btn-primary whitespace-nowrap" disabled={!inicio||!fim||loading} onClick={checar}>{loading?'Checando…':'Executar checagem'}</button></div></div></section>
  {msg&&<div className="rounded-xl border border-blue-200 bg-blue-50 p-3 text-sm text-blue-800">{msg}</div>}
  <section className="rounded-2xl border bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div><h2 className="font-semibold text-slate-900">Correspondências seguras</h2><p className="text-xs text-slate-500">Nome + valor + unidade. A competência válida é a do dado importado.</p></div><div className="flex items-center gap-2"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600">{sugestoes.length} sugestões</span><button className="btn-primary text-sm" disabled={!selecionadas||!!acao} onClick={confirmarSelecionadas}>{acao==='lote'?'Confirmando…':`Confirmar selecionados (${selecionadas})`}</button></div></div>
   {!inicio||!fim?<Vazio titulo="Selecione o período" texto="Informe os meses inicial e final e execute a checagem."/>:loading?<Vazio titulo="Comparando dados" texto="Analisando profissionais e notas sem alterar a conferência."/>:sugestoes.length===0?<Vazio titulo="Nenhuma sugestão disponível" texto="Execute a checagem ou ajuste o período e a unidade."/>:<div className="divide-y">{sugestoes.map(s=><article key={s.id} className="p-4 hover:bg-slate-50/70"><div className="grid items-center gap-3 lg:grid-cols-[32px_1fr_42px_1fr_auto]"><input aria-label="Selecionar sugestão" type="checkbox" className="h-4 w-4" checked={s.selecionada} onChange={e=>setSugestoes(v=>v.map(x=>x.id===s.id?{...x,selecionada:e.target.checked}:x))}/><Cartao rotulo="Profissional importado" nome={s.profissional.nome||'—'} doc={s.profissional.documento} valor={s.profissional.valor_comissao} detalhe={`${s.profissional.empresaNome} · competência oficial ${fmtMes(s.profissional.mes_ref)}`}/><div className="flex h-9 w-9 items-center justify-center rounded-full bg-emerald-100 text-lg font-bold text-emerald-700">=</div><Cartao rotulo="Nota recebida" nome={s.nota.nome||'—'} doc={s.nota.documento} valor={s.nota.nf_valor} detalhe={`NF ${s.nota.nf_numero||'—'} · competência informada ${fmtMes(s.nota.mes_ref)} · emissão ${fmtData(s.nota.nf_data)}`}/><button className="rounded-xl bg-emerald-600 px-4 py-3 text-sm font-bold text-white hover:bg-emerald-500 disabled:opacity-50" disabled={!!acao} onClick={()=>confirmar(s)}>{acao===s.id?'Confirmando…':'Dar OK'}</button></div></article>)}</div>}
  </section>
 </div></LayoutAdmin>}
function Cartao({rotulo,nome,doc,valor,detalhe}:{rotulo:string;nome:string;doc:string|null;valor:number|null;detalhe:string}){return <div className="rounded-xl border border-slate-200 bg-white p-3"><span className="text-[10px] font-bold uppercase tracking-wide text-slate-400">{rotulo}</span><div className="mt-1 flex justify-between gap-3"><b className="text-sm text-slate-900">{nome}</b><b className="whitespace-nowrap text-sm text-slate-900">{formatarMoeda(valor||0)}</b></div><p className="mt-1 text-xs text-slate-500">{doc||'Documento não informado'}</p><p className="mt-1 text-[11px] text-slate-400">{detalhe}</p></div>}
function Vazio({titulo,texto}:{titulo:string;texto:string}){return <div className="px-4 py-16 text-center"><p className="text-sm font-semibold text-slate-600">{titulo}</p><p className="mt-1 text-xs text-slate-400">{texto}</p></div>}
