'use client'
import { useCallback,useEffect,useState } from 'react'
import { useRouter } from 'next/navigation'
import LayoutAdmin from '../../../components/LayoutAdmin'
import { supabase } from '../../../lib/supabase'
import { SALAO_ENABLED } from '../../../lib/salao/config'
import { historicoConferencia,restaurarNota } from '../../../lib/salao/conferencia'
type Nota={id:string;emitente_nome:string|null;documento:string|null;numero:string|null;valor:number|null;excluido_em:string|null;exclusao_motivo:string|null;excluido_por:string|null}
export default function AuditoriaPage(){
 const router=useRouter();const[aba,setAba]=useState<'historico'|'excluidas'>('historico');const[historico,setHistorico]=useState<Record<string,unknown>[]>([]);const[notas,setNotas]=useState<Nota[]>([]);const[loading,setLoading]=useState(false);const[msg,setMsg]=useState('')
 useEffect(()=>{if(!SALAO_ENABLED)router.replace('/dashboard')},[router])
 const carregar=useCallback(async()=>{setLoading(true);try{if(aba==='historico')setHistorico(await historicoConferencia({limite:1000}));else{const{data,error}=await supabase.from('salon_notas').select('id,emitente_nome,documento,numero,valor,excluido_em,exclusao_motivo,excluido_por').not('excluido_em','is',null).order('excluido_em',{ascending:false}).limit(1000);if(error)throw error;setNotas((data||[]) as Nota[])}}catch(e){setMsg(e instanceof Error?e.message:'Erro ao consultar auditoria.')}finally{setLoading(false)}},[aba])
 useEffect(()=>{if(SALAO_ENABLED)carregar()},[carregar])
 async function restaurar(id:string){if(!confirm('Restaurar esta nota?'))return;const{data}=await supabase.auth.getUser();const r=await restaurarNota(id,data.user?.email);if(!r.ok){setMsg(r.erro||'Erro ao restaurar.');return}setMsg('Nota restaurada e registrada no histórico.');carregar()}
 if(!SALAO_ENABLED)return null
 return <LayoutAdmin title="Salão — Histórico e Notas Excluídas"><div className="space-y-4">{msg&&<div className="rounded-lg border border-blue-200 bg-blue-50 p-3 text-sm text-blue-800">{msg}</div>}<div className="card flex gap-2"><button className={aba==='historico'?'btn-primary':'btn-secondary'} onClick={()=>setAba('historico')}>Histórico unificado</button><button className={aba==='excluidas'?'btn-primary':'btn-secondary'} onClick={()=>setAba('excluidas')}>Notas excluídas</button></div><div className="card">{loading?<div className="py-12 text-center text-gray-400">Carregando...</div>:aba==='historico'?<div className="overflow-x-auto"><table className="w-full"><thead><tr className="border-b bg-gray-50"><th className="table-header">Data/hora</th><th className="table-header">Ação</th><th className="table-header">Registro</th><th className="table-header">Anterior</th><th className="table-header">Novo</th><th className="table-header">Usuário</th><th className="table-header">Justificativa</th></tr></thead><tbody className="divide-y">{historico.map((h,i)=><tr key={String(h.id||i)}><td className="table-cell text-xs">{h.criado_em?new Date(String(h.criado_em)).toLocaleString('pt-BR'):'—'}</td><td className="table-cell">{String(h.acao||'')}</td><td className="table-cell">{String(h.tipo_ref||'')} {String(h.ref_id||'')}</td><td className="table-cell max-w-xs truncate text-xs">{h.antes?JSON.stringify(h.antes):'—'}</td><td className="table-cell max-w-xs truncate text-xs">{h.depois?JSON.stringify(h.depois):'—'}</td><td className="table-cell">{String(h.usuario||'—')}</td><td className="table-cell">{String(h.justificativa||'—')}</td></tr>)}</tbody></table></div>:<div className="overflow-x-auto"><table className="w-full"><thead><tr className="border-b bg-gray-50"><th className="table-header">Emitente</th><th className="table-header">CPF/CNPJ</th><th className="table-header">Nota</th><th className="table-header">Motivo</th><th className="table-header">Exclusão</th><th className="table-header text-right">Ação</th></tr></thead><tbody className="divide-y">{notas.map(n=><tr key={n.id}><td className="table-cell font-medium">{n.emitente_nome||'—'}</td><td className="table-cell">{n.documento||'—'}</td><td className="table-cell">{n.numero||'—'}</td><td className="table-cell">{n.exclusao_motivo||'—'}</td><td className="table-cell text-xs">{n.excluido_em?new Date(n.excluido_em).toLocaleString('pt-BR'):'—'} · {n.excluido_por||'—'}</td><td className="table-cell text-right"><button className="text-sm font-medium text-emerald-700" onClick={()=>restaurar(n.id)}>Restaurar</button></td></tr>)}</tbody></table></div>}</div></div></LayoutAdmin>
}
