'use client'
import { useCallback,useDeferredValue,useEffect,useMemo,useState } from 'react'
import { useRouter } from 'next/navigation'
import LayoutAdmin from '../../../components/LayoutAdmin'
import { supabase } from '../../../lib/supabase'
import { SALAO_ENABLED } from '../../../lib/salao/config'
import { historicoConferencia,restaurarNota } from '../../../lib/salao/conferencia'
import { formatarMoeda } from '../../../utils/calculoVT'

type Nota={id:string;emitente_nome:string|null;documento:string|null;numero:string|null;valor:number|null;excluida_em:string|null;excluida_motivo:string|null;excluida_por:string|null}
function jsonCurto(v:unknown){if(v==null)return '—';try{return JSON.stringify(v)}catch{return String(v)}}
function acaoLabel(v:unknown){return String(v||'').replaceAll('_',' ').replace(/^./,s=>s.toUpperCase())}

export default function AuditoriaPage(){
 const router=useRouter();const[aba,setAba]=useState<'historico'|'excluidas'>('historico');const[historico,setHistorico]=useState<Record<string,unknown>[]>([]);const[notas,setNotas]=useState<Nota[]>([]);const[loading,setLoading]=useState(false);const[msg,setMsg]=useState('');const[busca,setBusca]=useState('');const buscaD=useDeferredValue(busca)
 useEffect(()=>{if(!SALAO_ENABLED)router.replace('/dashboard')},[router])
 const carregar=useCallback(async()=>{setLoading(true);setMsg('');try{if(aba==='historico')setHistorico(await historicoConferencia({limite:1000}));else{const{data,error}=await supabase.from('salon_notas').select('id,emitente_nome,documento,numero,valor,excluida_em,excluida_motivo,excluida_por').eq('excluida',true).order('excluida_em',{ascending:false}).limit(1000);if(error)throw error;setNotas((data||[]) as Nota[])}}catch(e){setMsg(e instanceof Error?e.message:'Erro ao consultar auditoria.')}finally{setLoading(false)}},[aba])
 useEffect(()=>{if(SALAO_ENABLED)carregar()},[carregar])
 const histVis=useMemo(()=>{const q=buscaD.trim().toLowerCase();return q?historico.filter(h=>`${h.acao} ${h.tipo} ${h.ref_id} ${h.usuario} ${h.justificativa}`.toLowerCase().includes(q)):historico},[historico,buscaD])
 const notasVis=useMemo(()=>{const q=buscaD.trim().toLowerCase();return q?notas.filter(n=>`${n.emitente_nome} ${n.documento} ${n.numero} ${n.excluida_motivo}`.toLowerCase().includes(q)):notas},[notas,buscaD])
 async function restaurar(id:string){const{data}=await supabase.auth.getUser();const r=await restaurarNota(id,data.user?.email);if(!r.ok){setMsg(r.erro||'Erro ao restaurar.');return}setNotas(v=>v.filter(n=>n.id!==id));setMsg('Nota restaurada e registrada no histórico.')}
 if(!SALAO_ENABLED)return null
 return <LayoutAdmin title="Salão — Auditoria"><div className="space-y-4">
  {msg&&<div className="rounded-lg border border-blue-200 bg-blue-50 p-3 text-sm text-blue-800">{msg}</div>}
  <section className="rounded-xl border bg-white p-3 shadow-sm"><div className="flex flex-wrap items-center gap-2"><div className="flex rounded-lg bg-slate-100 p-1"><button className={`rounded-md px-3 py-2 text-sm font-medium ${aba==='historico'?'bg-white text-slate-900 shadow-sm':'text-slate-500'}`} onClick={()=>{setAba('historico');setBusca('')}}>Histórico</button><button className={`rounded-md px-3 py-2 text-sm font-medium ${aba==='excluidas'?'bg-white text-slate-900 shadow-sm':'text-slate-500'}`} onClick={()=>{setAba('excluidas');setBusca('')}}>Notas excluídas</button></div><input type="search" className="input-field ml-auto max-w-md" placeholder="Buscar ação, nota, usuário ou motivo" value={busca} onChange={e=>setBusca(e.target.value)}/><button className="btn-secondary text-sm" onClick={carregar}>Atualizar</button></div></section>
  <section className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b p-3"><div><h2 className="font-semibold">{aba==='historico'?'Movimentações do módulo':'Lixeira de notas'}</h2><p className="text-xs text-gray-500">{aba==='historico'?histVis.length:notasVis.length} registro(s) visível(is)</p></div></div>
  {loading?<div className="py-14 text-center text-sm text-gray-400">Carregando auditoria…</div>:aba==='historico'?(histVis.length?<div className="overflow-x-auto"><table className="w-full"><thead><tr className="border-b bg-gray-50"><th className="table-header">Data/hora</th><th className="table-header">Ação</th><th className="table-header">Tipo/registro</th><th className="table-header">Anterior</th><th className="table-header">Novo</th><th className="table-header">Usuário</th><th className="table-header">Justificativa</th></tr></thead><tbody className="divide-y">{histVis.map((h,i)=><tr key={String(h.id||i)} className="hover:bg-slate-50"><td className="table-cell whitespace-nowrap text-xs">{h.criado_em?new Date(String(h.criado_em)).toLocaleString('pt-BR'):'—'}</td><td className="table-cell"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-medium text-slate-700">{acaoLabel(h.acao)}</span></td><td className="table-cell text-xs">{String(h.tipo||'—')}<span className="block max-w-40 truncate text-gray-400">{String(h.ref_id||'')}</span></td><td className="table-cell max-w-56"><span title={jsonCurto(h.valor_anterior)} className="block truncate text-xs">{jsonCurto(h.valor_anterior)}</span></td><td className="table-cell max-w-56"><span title={jsonCurto(h.valor_novo)} className="block truncate text-xs">{jsonCurto(h.valor_novo)}</span></td><td className="table-cell text-xs">{String(h.usuario||'—')}</td><td className="table-cell text-xs">{String(h.justificativa||'—')}</td></tr>)}</tbody></table></div>:<Vazio texto="Nenhuma movimentação encontrada."/>):(notasVis.length?<div className="overflow-x-auto"><table className="w-full"><thead><tr className="border-b bg-gray-50"><th className="table-header">Emitente</th><th className="table-header">CPF/CNPJ</th><th className="table-header">Nota</th><th className="table-header text-right">Valor</th><th className="table-header">Motivo</th><th className="table-header">Exclusão</th><th className="table-header text-right">Ação</th></tr></thead><tbody className="divide-y">{notasVis.map(n=><tr key={n.id} className="hover:bg-slate-50"><td className="table-cell font-medium">{n.emitente_nome||'—'}</td><td className="table-cell text-xs">{n.documento||'—'}</td><td className="table-cell">{n.numero||'—'}</td><td className="table-cell text-right">{formatarMoeda(n.valor||0)}</td><td className="table-cell">{n.excluida_motivo||'—'}</td><td className="table-cell text-xs">{n.excluida_em?new Date(n.excluida_em).toLocaleString('pt-BR'):'—'}<span className="block text-gray-400">{n.excluida_por||'—'}</span></td><td className="table-cell text-right"><button className="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-700 hover:bg-emerald-100" onClick={()=>restaurar(n.id)}>Restaurar</button></td></tr>)}</tbody></table></div>:<Vazio texto="Nenhuma nota excluída encontrada."/>)}</section>
 </div></LayoutAdmin>
}
function Vazio({texto}:{texto:string}){return <div className="py-14 text-center"><p className="text-sm font-medium text-gray-600">{texto}</p><p className="mt-1 text-xs text-gray-400">Altere a busca ou atualize os dados.</p></div>}
